// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/advisories/
// Wire into a form with: useForm({ resolver: zodResolver(<schema>) }).

import { z } from 'zod';

export const advisoriesCreateSchema = z.object({
  title: z.string({ required_error: 'Title is required' }).min(1, 'Title is required'),
  content: z.string({ required_error: 'Content is required' }).min(1, 'Content is required'),
  target_crop_ids: z.array(z.string()).optional(),
  target_district_ids: z.array(z.string()).optional(),
  farmer_segment: z.string().optional(),
  linked_alert_id: z.string().optional(),
  status: z.string().optional(),
});
export type AdvisoriesCreateInput = z.infer<typeof advisoriesCreateSchema>;

export const advisoriesUpdateSchema = z.object({
  title: z.string().optional(),
  content: z.string().optional(),
  target_crop_ids: z.array(z.string()).optional(),
  target_district_ids: z.array(z.string()).optional(),
  farmer_segment: z.string().optional(),
  linked_alert_id: z.string().optional(),
  status: z.string().optional(),
});
export type AdvisoriesUpdateInput = z.infer<typeof advisoriesUpdateSchema>;
