// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/advisories/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface AdvisoriesDeleteParams {
  id: string;
}
export interface AdvisoriesDeleteResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface AdvisoriesCoverageParams {
  district?: string;
  season?: string;
  page?: number;
  limit?: number;
  search?: string;
}
export interface AdvisoriesCoverageResponse {
  message: string;
  data: Array<{
    alert_id?: string;
    alert_title?: string;
    alert_level?: string;
    crop?: string;
    has_advisory?: boolean;
    advisory_id?: string;
    advisory_title?: string;
    advisory_status?: string;
    issued_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface AdvisoriesDetailParams {
  id?: string;
}
export interface AdvisoriesDetailResponse {
  message?: string;
  data?: {
    id?: string;
    title?: string;
    content?: string;
    target_crops?: Array<string>;
    target_districts?: Array<string>;
    farmer_segment?: string;
    linked_alert_id?: string;
    status?: string;
    delivery_status?: Record<string, any>;
    created_by?: string;
    published_at?: string;
    created_at?: string;
    updated_at?: string;
  };
}

export interface AdvisoriesListParams {
  page?: number;
  limit?: number;
  status?: string;
  crop?: string;
  district?: string;
  search?: string;
}
export interface AdvisoriesListResponse {
  message: string;
  data: Array<{
    id?: string;
    title?: string;
    content?: string;
    target_crops?: Array<string>;
    target_districts?: Array<string>;
    status?: string;
    linked_alert_id?: string;
    created_by?: string;
    published_at?: string;
    created_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface AdvisoriesAssignParams {
  farmer_id: string;
  advisory_id: string;
}
export interface AdvisoriesAssignResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface AdvisoriesCreateParams {
  title: string;
  content: string;
  target_crop_ids: Array<string>;
  target_district_ids: Array<string>;
  farmer_segment: string;
  linked_alert_id: string;
  status: string;
}
export interface AdvisoriesCreateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface AdvisoriesUpdateParams {
  id: string;
  title: string;
  content: string;
  target_crop_ids: Array<string>;
  target_district_ids: Array<string>;
  farmer_segment: string;
  linked_alert_id: string;
  status: string;
}
export interface AdvisoriesUpdateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const advisoriesService = {
  delete: (data: AdvisoriesDeleteParams): Promise<AdvisoriesDeleteResponse> => apiService.delete<AdvisoriesDeleteResponse>({ endpoint: Endpoint.ADVISORIES.DELETE, data: (data ?? {}) as Record<string, any> }),
  coverage: (params?: AdvisoriesCoverageParams): Promise<AdvisoriesCoverageResponse> => apiService.get<AdvisoriesCoverageResponse>({ endpoint: Endpoint.ADVISORIES.COVERAGE, params: (params ?? {}) as Record<string, any> }),
  detail: (params?: AdvisoriesDetailParams): Promise<AdvisoriesDetailResponse> => apiService.get<AdvisoriesDetailResponse>({ endpoint: Endpoint.ADVISORIES.DETAIL, params: (params ?? {}) as Record<string, any> }),
  list: (params?: AdvisoriesListParams): Promise<AdvisoriesListResponse> => apiService.get<AdvisoriesListResponse>({ endpoint: Endpoint.ADVISORIES.LIST, params: (params ?? {}) as Record<string, any> }),
  assign: (data: AdvisoriesAssignParams): Promise<AdvisoriesAssignResponse> => apiService.post<AdvisoriesAssignResponse>({ endpoint: Endpoint.ADVISORIES.ASSIGN, data: (data ?? {}) as Record<string, any> }),
  create: (data: AdvisoriesCreateParams): Promise<AdvisoriesCreateResponse> => apiService.post<AdvisoriesCreateResponse>({ endpoint: Endpoint.ADVISORIES.CREATE, data: (data ?? {}) as Record<string, any> }),
  update: (data: AdvisoriesUpdateParams): Promise<AdvisoriesUpdateResponse> => apiService.put<AdvisoriesUpdateResponse>({ endpoint: Endpoint.ADVISORIES.UPDATE, data: (data ?? {}) as Record<string, any> }),
};

export default advisoriesService;
