// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/ai_models/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface AiModelsListParams {
  page?: number;
  limit?: number;
  model_type?: string;
  search?: string;
}
export interface AiModelsListResponse {
  message: string;
  data: Array<{
    id?: string;
    name?: string;
    model_type?: string;
    description?: string;
    version?: string;
    input_parameters?: Record<string, any>;
    output_description?: string;
    supported_crops?: Array<string>;
    last_updated?: string;
    version_history?: Array<{
      version?: string;
      released_at?: string;
      changes?: string;
    }>;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface AiModelsResultsParams {
  job_id?: string;
}
export interface AiModelsResultsResponse {
  message?: string;
  data?: {
    job_id?: string;
    model_name?: string;
    status?: string;
    predictions?: Array<{
      district?: string;
      crop?: string;
      predicted_value?: number;
      confidence?: number;
      metric?: string;
      date?: string;
    }>;
    chart_data?: Record<string, any>;
    download_url?: string;
    completed_at?: string;
  };
}

export interface AiModelsRunParams {
  model_id: string;
  dataset_ids: Array<string>;
  parameters: Record<string, any>;
  district: string;
  crop: string;
  season: string;
}
export interface AiModelsRunResponse {
  message?: string;
  data?: {
    job_id?: string;
    status?: string;
    estimated_completion?: string;
  };
}

export const aiModelsService = {
  list: (params?: AiModelsListParams): Promise<AiModelsListResponse> => apiService.get<AiModelsListResponse>({ endpoint: Endpoint.AI_MODELS.LIST, params: (params ?? {}) as Record<string, any> }),
  results: (params?: AiModelsResultsParams): Promise<AiModelsResultsResponse> => apiService.get<AiModelsResultsResponse>({ endpoint: Endpoint.AI_MODELS.RESULTS, params: (params ?? {}) as Record<string, any> }),
  run: (data: AiModelsRunParams): Promise<AiModelsRunResponse> => apiService.post<AiModelsRunResponse>({ endpoint: Endpoint.AI_MODELS.RUN, data: (data ?? {}) as Record<string, any> }),
};

export default aiModelsService;
