// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/alerts/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface AlertsActiveListParams {
  page?: number;
  limit?: number;
  district?: string;
  crop?: string;
  search?: string;
}
export interface AlertsActiveListResponse {
  message: string;
  data: Array<{
    id?: string;
    type?: string;
    alert_level?: string;
    title?: string;
    crop?: string;
    district?: string;
    issued_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface AlertsListParams {
  page?: number;
  limit?: number;
  district?: string;
  agro_ecological_zone?: string;
  alert_level?: string;
  search?: string;
}
export interface AlertsListResponse {
  message: string;
  data: Array<{
    id?: string;
    type?: string;
    alert_level?: string;
    title?: string;
    description?: string;
    district?: string;
    agro_ecological_zone?: string;
    issued_at?: string;
    expires_at?: string;
    affected_crops?: Array<string>;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export const alertsService = {
  activeList: (params?: AlertsActiveListParams): Promise<AlertsActiveListResponse> => apiService.get<AlertsActiveListResponse>({ endpoint: Endpoint.ALERTS.ACTIVE_LIST, params: (params ?? {}) as Record<string, any> }),
  list: (params?: AlertsListParams): Promise<AlertsListResponse> => apiService.get<AlertsListResponse>({ endpoint: Endpoint.ALERTS.LIST, params: (params ?? {}) as Record<string, any> }),
};

export default alertsService;
