// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/beneficiaries/
// Wire into a form with: useForm({ resolver: zodResolver(<schema>) }).

import { z } from 'zod';

export const beneficiariesCreateSchema = z.object({
  full_name: z.string({ required_error: 'Full name is required' }).min(1, 'Full name is required'),
  phone_number: z.string().optional(),
  district: z.string().optional(),
  sub_county: z.string().optional(),
  programme_id: z.string().optional(),
  crop_ids: z.array(z.string()).optional(),
  enrolment_date: z.string().optional(),
  intervention_type: z.string().optional(),
  gps_lat: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  gps_lng: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
});
export type BeneficiariesCreateInput = z.infer<typeof beneficiariesCreateSchema>;

export const beneficiariesUpdateSchema = z.object({
  notes: z.string().optional(),
  flagged_for_followup: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  practice_adoption_status: z.string().optional(),
  enrolment_status: z.string().optional(),
});
export type BeneficiariesUpdateInput = z.infer<typeof beneficiariesUpdateSchema>;
