// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/beneficiaries/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface BeneficiariesDeleteParams {
  id: string;
}
export interface BeneficiariesDeleteResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface BeneficiariesDetailParams {
  id?: string;
}
export interface BeneficiariesDetailResponse {
  message?: string;
  data?: {
    id?: string;
    full_name?: string;
    phone_number?: string;
    district?: string;
    sub_county?: string;
    programme_id?: string;
    enrolment_status?: string;
    crops?: Array<string>;
    farm_registrations?: Array<{
      farm_id?: string;
      farm_name?: string;
      gps_lat?: number;
      gps_lng?: number;
    }>;
    inputs_received?: Array<{
      input_type?: string;
      quantity?: number;
      date?: string;
    }>;
    training_sessions?: Array<{
      title?: string;
      date?: string;
      assessment_result?: string;
    }>;
    practice_adoption_evidence?: string;
    outcome_measurements?: Array<{
      season?: string;
      yield_kg_ha?: number;
      income_usd?: number;
      recorded_at?: string;
    }>;
    enrolment_date?: string;
  };
}

export interface BeneficiariesListParams {
  page?: number;
  limit?: number;
  district?: string;
  crop?: string;
  programme_id?: string;
  intervention_type?: string;
  enrolment_from?: string;
  enrolment_to?: string;
  search?: string;
}
export interface BeneficiariesListResponse {
  message: string;
  data: Array<{
    id?: string;
    full_name?: string;
    district?: string;
    sub_county?: string;
    programme_id?: string;
    enrolment_status?: string;
    crops?: Array<string>;
    enrolment_date?: string;
    last_outcome_date?: string;
    practice_adoption_status?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export type BeneficiariesStatsParams = Record<string, any>;
export interface BeneficiariesStatsResponse {
  message?: string;
  data?: {
    total_beneficiaries?: number;
    active?: number;
    disengaged?: number;
    by_district?: Array<{
      district?: string;
      count?: number;
    }>;
    by_programme?: Array<{
      programme?: string;
      count?: number;
    }>;
    by_crop?: Array<{
      crop?: string;
      count?: number;
    }>;
  };
}

export interface BeneficiariesCreateParams {
  full_name: string;
  phone_number: string;
  district: string;
  sub_county: string;
  programme_id: string;
  crop_ids: Array<string>;
  enrolment_date: string;
  intervention_type: string;
  gps_lat: number;
  gps_lng: number;
}
export interface BeneficiariesCreateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface BeneficiariesUpdateParams {
  id: string;
  notes: string;
  flagged_for_followup: boolean;
  practice_adoption_status: string;
  enrolment_status: string;
}
export interface BeneficiariesUpdateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const beneficiariesService = {
  delete: (data: BeneficiariesDeleteParams): Promise<BeneficiariesDeleteResponse> => apiService.delete<BeneficiariesDeleteResponse>({ endpoint: Endpoint.BENEFICIARIES.DELETE, data: (data ?? {}) as Record<string, any> }),
  detail: (params?: BeneficiariesDetailParams): Promise<BeneficiariesDetailResponse> => apiService.get<BeneficiariesDetailResponse>({ endpoint: Endpoint.BENEFICIARIES.DETAIL, params: (params ?? {}) as Record<string, any> }),
  list: (params?: BeneficiariesListParams): Promise<BeneficiariesListResponse> => apiService.get<BeneficiariesListResponse>({ endpoint: Endpoint.BENEFICIARIES.LIST, params: (params ?? {}) as Record<string, any> }),
  stats: (params?: BeneficiariesStatsParams): Promise<BeneficiariesStatsResponse> => apiService.get<BeneficiariesStatsResponse>({ endpoint: Endpoint.BENEFICIARIES.STATS, params: (params ?? {}) as Record<string, any> }),
  create: (data: BeneficiariesCreateParams): Promise<BeneficiariesCreateResponse> => apiService.post<BeneficiariesCreateResponse>({ endpoint: Endpoint.BENEFICIARIES.CREATE, data: (data ?? {}) as Record<string, any> }),
  update: (data: BeneficiariesUpdateParams): Promise<BeneficiariesUpdateResponse> => apiService.put<BeneficiariesUpdateResponse>({ endpoint: Endpoint.BENEFICIARIES.UPDATE, data: (data ?? {}) as Record<string, any> }),
};

export default beneficiariesService;
