// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/crops/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface CropsListParams {
  page?: number;
  limit?: number;
  search?: string;
}
export interface CropsListResponse {
  message: string;
  data: Array<{
    id?: string;
    name?: string;
    description?: string;
    season?: string;
    agro_ecological_zones?: Array<string>;
    image_url?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export const cropsService = {
  list: (params?: CropsListParams): Promise<CropsListResponse> => apiService.get<CropsListResponse>({ endpoint: Endpoint.CROPS.LIST, params: (params ?? {}) as Record<string, any> }),
};

export default cropsService;
