// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/custom_queries/
// Wire into a form with: useForm({ resolver: zodResolver(<schema>) }).

import { z } from 'zod';

export const customQueriesCreateSchema = z.object({
  name: z.string({ required_error: 'Name is required' }).min(1, 'Name is required'),
  description: z.string().optional(),
  dataset_ids: z.array(z.string()).optional(),
  filters: z.any().optional(),
  aggregations: z.any().optional(),
  joins: z.any().optional(),
  shared: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
});
export type CustomQueriesCreateInput = z.infer<typeof customQueriesCreateSchema>;

export const customQueriesUpdateSchema = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  dataset_ids: z.array(z.string()).optional(),
  filters: z.any().optional(),
  aggregations: z.any().optional(),
  joins: z.any().optional(),
  shared: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
});
export type CustomQueriesUpdateInput = z.infer<typeof customQueriesUpdateSchema>;
