// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/custom_queries/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface CustomQueriesDeleteParams {
  id: string;
}
export interface CustomQueriesDeleteResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface CustomQueriesDetailParams {
  id?: string;
}
export interface CustomQueriesDetailResponse {
  message?: string;
  data?: {
    id?: string;
    name?: string;
    description?: string;
    dataset_ids?: Array<string>;
    filters?: Record<string, any>;
    aggregations?: Record<string, any>;
    joins?: Record<string, any>;
    shared?: boolean;
    created_by?: string;
    created_at?: string;
    updated_at?: string;
  };
}

export interface CustomQueriesListParams {
  page?: number;
  limit?: number;
  search?: string;
}
export interface CustomQueriesListResponse {
  message: string;
  data: Array<{
    id?: string;
    name?: string;
    description?: string;
    datasets_used?: Array<string>;
    filter_config?: Record<string, any>;
    aggregation_config?: Record<string, any>;
    created_by?: string;
    shared?: boolean;
    created_at?: string;
    updated_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface CustomQueriesCreateParams {
  name: string;
  description: string;
  dataset_ids: Array<string>;
  filters: Record<string, any>;
  aggregations: Record<string, any>;
  joins: Record<string, any>;
  shared: boolean;
}
export interface CustomQueriesCreateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface CustomQueriesExecuteParams {
  dataset_ids: Array<string>;
  filters: Record<string, any>;
  aggregations: Record<string, any>;
  joins: Record<string, any>;
  page: number;
  limit: number;
}
export interface CustomQueriesExecuteResponse {
  message?: string;
  data?: {
    columns?: Array<{
      name?: string;
      type?: string;
    }>;
    rows?: Array<Record<string, any>>;
    total?: number;
    page?: number;
    limit?: number;
    totalPages?: number;
  };
}

export interface CustomQueriesUpdateParams {
  id: string;
  name: string;
  description: string;
  dataset_ids: Array<string>;
  filters: Record<string, any>;
  aggregations: Record<string, any>;
  joins: Record<string, any>;
  shared: boolean;
}
export interface CustomQueriesUpdateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const customQueriesService = {
  delete: (data: CustomQueriesDeleteParams): Promise<CustomQueriesDeleteResponse> => apiService.delete<CustomQueriesDeleteResponse>({ endpoint: Endpoint.CUSTOM_QUERIES.DELETE, data: (data ?? {}) as Record<string, any> }),
  detail: (params?: CustomQueriesDetailParams): Promise<CustomQueriesDetailResponse> => apiService.get<CustomQueriesDetailResponse>({ endpoint: Endpoint.CUSTOM_QUERIES.DETAIL, params: (params ?? {}) as Record<string, any> }),
  list: (params?: CustomQueriesListParams): Promise<CustomQueriesListResponse> => apiService.get<CustomQueriesListResponse>({ endpoint: Endpoint.CUSTOM_QUERIES.LIST, params: (params ?? {}) as Record<string, any> }),
  create: (data: CustomQueriesCreateParams): Promise<CustomQueriesCreateResponse> => apiService.post<CustomQueriesCreateResponse>({ endpoint: Endpoint.CUSTOM_QUERIES.CREATE, data: (data ?? {}) as Record<string, any> }),
  execute: (data: CustomQueriesExecuteParams): Promise<CustomQueriesExecuteResponse> => apiService.post<CustomQueriesExecuteResponse>({ endpoint: Endpoint.CUSTOM_QUERIES.EXECUTE, data: (data ?? {}) as Record<string, any> }),
  update: (data: CustomQueriesUpdateParams): Promise<CustomQueriesUpdateResponse> => apiService.put<CustomQueriesUpdateResponse>({ endpoint: Endpoint.CUSTOM_QUERIES.UPDATE, data: (data ?? {}) as Record<string, any> }),
};

export default customQueriesService;
