// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/data_hub/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface DataHubDatasetsParams {
  page?: number;
  limit?: number;
  category?: string;
  search?: string;
}
export interface DataHubDatasetsResponse {
  message: string;
  data: Array<{
    id?: string;
    name?: string;
    category?: string;
    description?: string;
    source?: string;
    frequency?: string;
    spatial_coverage?: string;
    temporal_coverage?: string;
    record_count?: number;
    last_updated?: string;
    format?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface DataHubPreviewParams {
  dataset_id?: string;
  limit?: number;
}
export interface DataHubPreviewResponse {
  message?: string;
  data?: {
    dataset_id?: string;
    dataset_name?: string;
    columns?: Array<{
      name?: string;
      type?: string;
      description?: string;
    }>;
    sample_records?: Array<Record<string, any>>;
    total_records?: number;
  };
}

export const dataHubService = {
  datasets: (params?: DataHubDatasetsParams): Promise<DataHubDatasetsResponse> => apiService.get<DataHubDatasetsResponse>({ endpoint: Endpoint.DATA_HUB.DATASETS, params: (params ?? {}) as Record<string, any> }),
  preview: (params?: DataHubPreviewParams): Promise<DataHubPreviewResponse> => apiService.get<DataHubPreviewResponse>({ endpoint: Endpoint.DATA_HUB.PREVIEW, params: (params ?? {}) as Record<string, any> }),
};

export default dataHubService;
