// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/districts/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface DistrictsListParams {
  page?: number;
  limit?: number;
  search?: string;
}
export interface DistrictsListResponse {
  message: string;
  data: Array<{
    id?: string;
    name?: string;
    region?: string;
    agro_ecological_zone?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export const districtsService = {
  list: (params?: DistrictsListParams): Promise<DistrictsListResponse> => apiService.get<DistrictsListResponse>({ endpoint: Endpoint.DISTRICTS.LIST, params: (params ?? {}) as Record<string, any> }),
};

export default districtsService;
