// AUTO-GENERATED by mock-codegen — do not edit.
// Source of truth: /planner/api_details/**/*.json

export const Endpoint = {
  ADVISORIES: {
    DELETE: '/advisories/delete',
    COVERAGE: '/advisories/coverage',
    DETAIL: '/advisories/detail',
    LIST: '/advisories/list',
    ASSIGN: '/advisories/assign',
    CREATE: '/advisories/create',
    UPDATE: '/advisories/update',
  },
  AI_MODELS: {
    LIST: '/ai-models/list',
    RESULTS: '/ai-models/results',
    RUN: '/ai-models/run',
  },
  ALERTS: {
    ACTIVE_LIST: '/alerts/active/list',
    LIST: '/alerts/list',
  },
  BENEFICIARIES: {
    DELETE: '/beneficiaries/delete',
    DETAIL: '/beneficiaries/detail',
    LIST: '/beneficiaries/list',
    STATS: '/beneficiaries/stats',
    CREATE: '/beneficiaries/create',
    UPDATE: '/beneficiaries/update',
  },
  CROPS: {
    LIST: '/crops/list',
  },
  CUSTOM_QUERIES: {
    DELETE: '/custom-queries/delete',
    DETAIL: '/custom-queries/detail',
    LIST: '/custom-queries/list',
    CREATE: '/custom-queries/create',
    EXECUTE: '/custom-queries/execute',
    UPDATE: '/custom-queries/update',
  },
  DATA_HUB: {
    DATASETS: '/data-hub/datasets',
    PREVIEW: '/data-hub/preview',
  },
  DISTRICTS: {
    LIST: '/districts/list',
  },
  FARM_ACTIVITIES: {
    DELETE: '/farm-activities/delete',
    DETAIL: '/farm-activities/detail',
    LIST: '/farm-activities/list',
    CREATE: '/farm-activities/create',
    UPDATE: '/farm-activities/update',
  },
  FARM_MANAGEMENT: {
    STATS: '/farm-management/stats',
  },
  FARMERS: {
    DELETE: '/farmers/delete',
    DETAIL: '/farmers/detail',
    LIST: '/farmers/list',
    CREATE: '/farmers/create',
    UPDATE: '/farmers/update',
  },
  FARMING_PRACTICES: {
    LIST: '/farming-practices/list',
  },
  FARMS: {
    DELETE: '/farms/delete',
    DETAIL: '/farms/detail',
    LIST: '/farms/list',
    CREATE: '/farms/create',
    UPDATE: '/farms/update',
  },
  FIELD_VISITS: {
    DELETE: '/field-visits/delete',
    DETAIL: '/field-visits/detail',
    EXPORT: '/field-visits/export',
    LIST: '/field-visits/list',
    CREATE: '/field-visits/create',
    UPDATE: '/field-visits/update',
  },
  IMPACT: {
    ASSESSMENT_LIST: '/impact/assessment/list',
    ASSESSMENT_RESULTS: '/impact/assessment/results',
    BASELINE_LIST: '/impact/baseline/list',
    ASSESSMENT_RUN: '/impact/assessment/run',
    BENEFICIARY_LINK: '/impact/beneficiary/link',
  },
  INTEGRATIONS: {
    LIST: '/integrations/list',
    UPDATE: '/integrations/update',
  },
  MAPS: {
    CROP_ZONES: '/maps/crop-zones',
    DISTRICT_PRODUCTION: '/maps/district-production',
    DISTRICT_STATS: '/maps/district-stats',
    EXTENSION_COVERAGE: '/maps/extension-coverage',
    FARMER_DENSITY: '/maps/farmer-density',
    PEST_ALERTS: '/maps/pest-alerts',
    WEATHER_OVERLAY: '/maps/weather-overlay',
  },
  MARKET_PRICES: {
    LIST: '/market-prices/list',
    TRENDS: '/market-prices/trends',
    UCDA: '/market-prices/ucda',
    UBOS: '/market-prices/ubos',
    DISTRICTS: '/market-prices/districts',
  },
  MONITORING: {
    PROGRAMMES_LIST: '/monitoring/programmes/list',
    STATS: '/monitoring/stats',
  },
  NATIONAL_STATISTICS: {
    PRODUCTION: '/national-statistics/production',
    TRENDS: '/national-statistics/trends',
  },
  NOTIFICATIONS: {
    PREFERENCES: '/notifications/preferences',
  },
  PEST_ALERTS: {
    LIST: '/pest-alerts/list',
  },
  PEST_REPORTS: {
    LIST: '/pest-reports/list',
    TRENDS: '/pest-reports/trends',
    GENERATE: '/pest-reports/generate',
  },
  PEST_SIGHTINGS: {
    DELETE: '/pest-sightings/delete',
    DETAIL: '/pest-sightings/detail',
    LIST: '/pest-sightings/list',
    CREATE: '/pest-sightings/create',
    UPDATE: '/pest-sightings/update',
  },
  PESTS: {
    LIST: '/pests/list',
  },
  POLICY: {
    ALERTS_SUMMARY: '/policy/alerts-summary',
    DISTRICT_MAP: '/policy/district-map',
    SEASON_TRENDS: '/policy/season-trends',
    STATS: '/policy/stats',
  },
  PRICE_ALERTS: {
    DELETE: '/price-alerts/delete',
    DETAIL: '/price-alerts/detail',
    LIST: '/price-alerts/list',
    CREATE: '/price-alerts/create',
    UPDATE: '/price-alerts/update',
  },
  PRODUCTION_REPORTS: {
    LIST: '/production-reports/list',
    TEMPLATES: '/production-reports/templates',
    GENERATE: '/production-reports/generate',
    SCHEDULE: '/production-reports/schedule',
  },
  PROGRAMME_KPIS: {
    DELETE: '/programme-kpis/delete',
    DETAIL: '/programme-kpis/detail',
    LIST: '/programme-kpis/list',
    CREATE: '/programme-kpis/create',
    UPDATE: '/programme-kpis/update',
  },
  PUBLIC_REPORTS: {
    LIST: '/public-reports/list',
  },
  RECOMMENDATIONS: {
    EARLY_WARNINGS: '/recommendations/early-warnings',
    LIST: '/recommendations/list',
  },
  REPORTS: {
    ALERTS_HISTORY: '/reports/alerts-history',
  },
  RESEARCH_OUTPUTS: {
    DELETE: '/research-outputs/delete',
    DETAIL: '/research-outputs/detail',
    LIST: '/research-outputs/list',
    CREATE: '/research-outputs/create',
    UPDATE: '/research-outputs/update',
  },
  SEASONAL_CALENDARS: {
    LIST: '/seasonal-calendars/list',
    PEST_RISK_WINDOWS: '/seasonal-calendars/pest-risk-windows',
  },
  STATISTICAL_ANALYSIS: {
    RESULTS: '/statistical-analysis/results',
    RUN: '/statistical-analysis/run',
  },
  TREATMENTS: {
    LIST: '/treatments/list',
  },
  USERS: {
    PROFILE: '/users/profile',
    PUT_PROFILE: '/users/profile',
  },
  VARIETIES: {
    LIST: '/varieties/list',
  },
  WEATHER: {
    CURRENT: '/weather/current',
    EXPORT: '/weather/export',
    FORECAST: '/weather/forecast',
    HISTORICAL: '/weather/historical',
    EXPORT_SCHEDULE: '/weather/export-schedule',
  },
  CROP_MONITORING: {
    SENSORS: '/crop-monitoring/sensors',
    NDVI_SERIES: '/crop-monitoring/ndvi-series',
    UAV_SCANS: '/crop-monitoring/uav-scans',
    TIMESERIES_ALERTS: '/crop-monitoring/timeseries-alerts',
    HEALTH_SUMMARY: '/crop-monitoring/health-summary',
  },
} as const;
