// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/farms/
// Wire into a form with: useForm({ resolver: zodResolver(<schema>) }).

import { z } from 'zod';

export const farmsCreateSchema = z.object({
  farm_name: z.string({ required_error: 'Farm name is required' }).min(1, 'Farm name is required'),
  district: z.string({ required_error: 'District is required' }).min(1, 'District is required'),
  agro_ecological_zone: z.string().optional(),
  area_hectares: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  soil_type: z.string().optional(),
  gps_boundary: z.string().optional(),
  crop_ids: z.array(z.string()).optional(),
});
export type FarmsCreateInput = z.infer<typeof farmsCreateSchema>;

export const farmsUpdateSchema = z.object({
  farm_name: z.string().optional(),
  area_hectares: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  soil_type: z.string().optional(),
  gps_boundary: z.string().optional(),
  crop_ids: z.array(z.string()).optional(),
  growth_stage: z.string().optional(),
});
export type FarmsUpdateInput = z.infer<typeof farmsUpdateSchema>;
