// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/farm_management/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export type FarmManagementStatsParams = Record<string, any>;
export interface FarmManagementStatsResponse {
  message?: string;
  data?: {
    total_farmers?: number;
    pending_visits?: number;
    active_alerts?: number;
    outstanding_advisories?: number;
    recent_alert_count?: number;
    advisory_compliance_rate?: number;
  };
}

export const farmManagementService = {
  stats: (params?: FarmManagementStatsParams): Promise<FarmManagementStatsResponse> => apiService.get<FarmManagementStatsResponse>({ endpoint: Endpoint.FARM_MANAGEMENT.STATS, params: (params ?? {}) as Record<string, any> }),
};

export default farmManagementService;
