// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/farms/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface FarmsDeleteParams {
  id: string;
}
export interface FarmsDeleteResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface FarmsDetailParams {
  id?: string;
}
export interface FarmsDetailResponse {
  message?: string;
  data?: {
    id?: string;
    farm_name?: string;
    district?: string;
    agro_ecological_zone?: string;
    area_hectares?: number;
    soil_type?: string;
    gps_boundary?: string;
    crops?: Array<{
      id?: string;
      name?: string;
      growth_stage?: string;
      planting_date?: string;
    }>;
    soil_analysis?: Record<string, any>;
    active_alerts?: number;
    created_at?: string;
    updated_at?: string;
  };
}

export interface FarmsListParams {
  page?: number;
  limit?: number;
  crop?: string;
  search?: string;
}
export interface FarmsListResponse {
  message: string;
  data: Array<{
    id?: string;
    farm_name?: string;
    district?: string;
    agro_ecological_zone?: string;
    area_hectares?: number;
    soil_type?: string;
    gps_boundary?: string;
    crops?: Array<string>;
    active_alerts?: number;
    last_activity_date?: string;
    created_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface FarmsCreateParams {
  farm_name: string;
  district: string;
  agro_ecological_zone: string;
  area_hectares: number;
  soil_type: string;
  gps_boundary: string;
  crop_ids: Array<string>;
}
export interface FarmsCreateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface FarmsUpdateParams {
  id: string;
  farm_name: string;
  area_hectares: number;
  soil_type: string;
  gps_boundary: string;
  crop_ids: Array<string>;
  growth_stage: string;
}
export interface FarmsUpdateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const farmsService = {
  delete: (data: FarmsDeleteParams): Promise<FarmsDeleteResponse> => apiService.delete<FarmsDeleteResponse>({ endpoint: Endpoint.FARMS.DELETE, data: (data ?? {}) as Record<string, any> }),
  detail: (params?: FarmsDetailParams): Promise<FarmsDetailResponse> => apiService.get<FarmsDetailResponse>({ endpoint: Endpoint.FARMS.DETAIL, params: (params ?? {}) as Record<string, any> }),
  list: (params?: FarmsListParams): Promise<FarmsListResponse> => apiService.get<FarmsListResponse>({ endpoint: Endpoint.FARMS.LIST, params: (params ?? {}) as Record<string, any> }),
  create: (data: FarmsCreateParams): Promise<FarmsCreateResponse> => apiService.post<FarmsCreateResponse>({ endpoint: Endpoint.FARMS.CREATE, data: (data ?? {}) as Record<string, any> }),
  update: (data: FarmsUpdateParams): Promise<FarmsUpdateResponse> => apiService.put<FarmsUpdateResponse>({ endpoint: Endpoint.FARMS.UPDATE, data: (data ?? {}) as Record<string, any> }),
};

export default farmsService;
