// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/farming_practices/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface FarmingPracticesListParams {
  page?: number;
  limit?: number;
  crop?: string;
  practice_type?: string;
  search?: string;
}
export interface FarmingPracticesListResponse {
  message: string;
  data: Array<{
    id?: string;
    title?: string;
    description?: string;
    crop?: string;
    practice_type?: string;
    source?: string;
    agro_ecological_zone?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export const farmingPracticesService = {
  list: (params?: FarmingPracticesListParams): Promise<FarmingPracticesListResponse> => apiService.get<FarmingPracticesListResponse>({ endpoint: Endpoint.FARMING_PRACTICES.LIST, params: (params ?? {}) as Record<string, any> }),
};

export default farmingPracticesService;
