// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/farmers/
// Wire into a form with: useForm({ resolver: zodResolver(<schema>) }).

import { z } from 'zod';

export const farmersCreateSchema = z.object({
  full_name: z.string({ required_error: 'Full name is required' }).min(1, 'Full name is required'),
  phone_number: z.string().optional(),
  email: z.string().email('Enter a valid email').optional().or(z.literal('')),
  district: z.string().optional(),
  sub_county: z.string().optional(),
  crop_ids: z.array(z.string()).optional(),
  sms_enabled: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  email_enabled: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
});
export type FarmersCreateInput = z.infer<typeof farmersCreateSchema>;

export const farmersUpdateSchema = z.object({
  full_name: z.string().optional(),
  phone_number: z.string().optional(),
  email: z.string().email('Enter a valid email').optional().or(z.literal('')),
  district: z.string().optional(),
  sub_county: z.string().optional(),
  sms_enabled: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  email_enabled: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
});
export type FarmersUpdateInput = z.infer<typeof farmersUpdateSchema>;
