// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/farm_activities/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface FarmActivitiesDeleteParams {
  id: string;
}
export interface FarmActivitiesDeleteResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface FarmActivitiesDetailParams {
  id?: string;
}
export interface FarmActivitiesDetailResponse {
  message?: string;
  data?: {
    id?: string;
    farm_id?: string;
    activity_date?: string;
    activity_type?: string;
    description?: string;
    observations?: string;
    inputs_used?: string;
    quantity?: number;
    notes?: string;
    created_at?: string;
    updated_at?: string;
  };
}

export interface FarmActivitiesListParams {
  farm_id?: string;
  page?: number;
  limit?: number;
  search?: string;
}
export interface FarmActivitiesListResponse {
  message: string;
  data: Array<{
    id?: string;
    farm_id?: string;
    activity_date?: string;
    activity_type?: string;
    description?: string;
    observations?: string;
    inputs_used?: string;
    quantity?: number;
    notes?: string;
    created_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface FarmActivitiesCreateParams {
  farm_id: string;
  activity_date: string;
  activity_type: string;
  description: string;
  observations: string;
  inputs_used: string;
  quantity: number;
  notes: string;
}
export interface FarmActivitiesCreateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface FarmActivitiesUpdateParams {
  id: string;
  activity_date: string;
  activity_type: string;
  description: string;
  observations: string;
  inputs_used: string;
  quantity: number;
  notes: string;
}
export interface FarmActivitiesUpdateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const farmActivitiesService = {
  delete: (data: FarmActivitiesDeleteParams): Promise<FarmActivitiesDeleteResponse> => apiService.delete<FarmActivitiesDeleteResponse>({ endpoint: Endpoint.FARM_ACTIVITIES.DELETE, data: (data ?? {}) as Record<string, any> }),
  detail: (params?: FarmActivitiesDetailParams): Promise<FarmActivitiesDetailResponse> => apiService.get<FarmActivitiesDetailResponse>({ endpoint: Endpoint.FARM_ACTIVITIES.DETAIL, params: (params ?? {}) as Record<string, any> }),
  list: (params?: FarmActivitiesListParams): Promise<FarmActivitiesListResponse> => apiService.get<FarmActivitiesListResponse>({ endpoint: Endpoint.FARM_ACTIVITIES.LIST, params: (params ?? {}) as Record<string, any> }),
  create: (data: FarmActivitiesCreateParams): Promise<FarmActivitiesCreateResponse> => apiService.post<FarmActivitiesCreateResponse>({ endpoint: Endpoint.FARM_ACTIVITIES.CREATE, data: (data ?? {}) as Record<string, any> }),
  update: (data: FarmActivitiesUpdateParams): Promise<FarmActivitiesUpdateResponse> => apiService.put<FarmActivitiesUpdateResponse>({ endpoint: Endpoint.FARM_ACTIVITIES.UPDATE, data: (data ?? {}) as Record<string, any> }),
};

export default farmActivitiesService;
