// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/farmers/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface FarmersDeleteParams {
  id: string;
}
export interface FarmersDeleteResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface FarmersDetailParams {
  id?: string;
}
export interface FarmersDetailResponse {
  message?: string;
  data?: {
    id?: string;
    full_name?: string;
    phone_number?: string;
    email?: string;
    district?: string;
    sub_county?: string;
    crops?: Array<string>;
    farms?: Array<{
      id?: string;
      farm_name?: string;
      area_hectares?: number;
    }>;
    advisory_history?: Array<{
      advisory_id?: string;
      title?: string;
      received_at?: string;
      compliance_status?: string;
    }>;
    field_visit_logs?: Array<{
      visit_id?: string;
      visit_date?: string;
      extension_worker?: string;
      summary?: string;
    }>;
    active_alert_status?: string;
    sms_enabled?: boolean;
    email_enabled?: boolean;
    registered_at?: string;
  };
}

export interface FarmersListParams {
  page?: number;
  limit?: number;
  district?: string;
  crop?: string;
  alert_status?: string;
  last_visit_before?: string;
  compliance_rate_below?: number;
  search?: string;
}
export interface FarmersListResponse {
  message: string;
  data: Array<{
    id?: string;
    full_name?: string;
    phone_number?: string;
    district?: string;
    crops?: Array<string>;
    active_alert_status?: string;
    last_visit_date?: string;
    advisory_compliance_rate?: number;
    registered_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface FarmersCreateParams {
  full_name: string;
  phone_number: string;
  email: string;
  district: string;
  sub_county: string;
  crop_ids: Array<string>;
  sms_enabled: boolean;
  email_enabled: boolean;
}
export interface FarmersCreateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface FarmersUpdateParams {
  id: string;
  full_name: string;
  phone_number: string;
  email: string;
  district: string;
  sub_county: string;
  sms_enabled: boolean;
  email_enabled: boolean;
}
export interface FarmersUpdateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const farmersService = {
  delete: (data: FarmersDeleteParams): Promise<FarmersDeleteResponse> => apiService.delete<FarmersDeleteResponse>({ endpoint: Endpoint.FARMERS.DELETE, data: (data ?? {}) as Record<string, any> }),
  detail: (params?: FarmersDetailParams): Promise<FarmersDetailResponse> => apiService.get<FarmersDetailResponse>({ endpoint: Endpoint.FARMERS.DETAIL, params: (params ?? {}) as Record<string, any> }),
  list: (params?: FarmersListParams): Promise<FarmersListResponse> => apiService.get<FarmersListResponse>({ endpoint: Endpoint.FARMERS.LIST, params: (params ?? {}) as Record<string, any> }),
  create: (data: FarmersCreateParams): Promise<FarmersCreateResponse> => apiService.post<FarmersCreateResponse>({ endpoint: Endpoint.FARMERS.CREATE, data: (data ?? {}) as Record<string, any> }),
  update: (data: FarmersUpdateParams): Promise<FarmersUpdateResponse> => apiService.put<FarmersUpdateResponse>({ endpoint: Endpoint.FARMERS.UPDATE, data: (data ?? {}) as Record<string, any> }),
};

export default farmersService;
