// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/farm_activities/
// Wire into a form with: useForm({ resolver: zodResolver(<schema>) }).

import { z } from 'zod';

export const farmActivitiesCreateSchema = z.object({
  farm_id: z.string({ required_error: 'Farm is required' }).min(1, 'Farm is required'),
  activity_date: z.string({ required_error: 'Activity date is required' }).min(1, 'Activity date is required'),
  activity_type: z.string({ required_error: 'Activity type is required' }).min(1, 'Activity type is required'),
  description: z.string().optional(),
  observations: z.string().optional(),
  inputs_used: z.string().optional(),
  quantity: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  notes: z.string().optional(),
});
export type FarmActivitiesCreateInput = z.infer<typeof farmActivitiesCreateSchema>;

export const farmActivitiesUpdateSchema = z.object({
  activity_date: z.string().optional(),
  activity_type: z.string().optional(),
  description: z.string().optional(),
  observations: z.string().optional(),
  inputs_used: z.string().optional(),
  quantity: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  notes: z.string().optional(),
});
export type FarmActivitiesUpdateInput = z.infer<typeof farmActivitiesUpdateSchema>;
