// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/field_visits/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface FieldVisitsDeleteParams {
  id: string;
}
export interface FieldVisitsDeleteResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface FieldVisitsDetailParams {
  id?: string;
}
export interface FieldVisitsDetailResponse {
  message?: string;
  data?: {
    id?: string;
    farmer_id?: string;
    farmer_name?: string;
    farm_id?: string;
    visit_date?: string;
    observations?: string;
    pest_sightings?: string;
    crop_condition?: string;
    soil_observations?: string;
    advisories_given?: string;
    follow_up_actions?: string;
    follow_up_due_date?: string;
    status?: string;
    created_at?: string;
    updated_at?: string;
  };
}

export interface FieldVisitsExportParams {
  district?: string;
  from_date?: string;
  to_date?: string;
  format?: string;
}
export interface FieldVisitsExportResponse {
  message?: string;
  data?: {
    download_url?: string;
    file_name?: string;
    generated_at?: string;
  };
}

export interface FieldVisitsListParams {
  page?: number;
  limit?: number;
  farmer_id?: string;
  status?: string;
  from_date?: string;
  to_date?: string;
  search?: string;
}
export interface FieldVisitsListResponse {
  message: string;
  data: Array<{
    id?: string;
    farmer_id?: string;
    farmer_name?: string;
    farm_id?: string;
    visit_date?: string;
    observations?: string;
    advisories_given?: string;
    follow_up_actions?: string;
    follow_up_due_date?: string;
    status?: string;
    created_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface FieldVisitsCreateParams {
  farmer_id: string;
  farm_id: string;
  visit_date: string;
  observations: string;
  pest_sightings: string;
  crop_condition: string;
  soil_observations: string;
  advisories_given: string;
  follow_up_actions: string;
  follow_up_due_date: string;
}
export interface FieldVisitsCreateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface FieldVisitsUpdateParams {
  id: string;
  observations: string;
  pest_sightings: string;
  crop_condition: string;
  advisories_given: string;
  follow_up_actions: string;
  follow_up_due_date: string;
  status: string;
}
export interface FieldVisitsUpdateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const fieldVisitsService = {
  delete: (data: FieldVisitsDeleteParams): Promise<FieldVisitsDeleteResponse> => apiService.delete<FieldVisitsDeleteResponse>({ endpoint: Endpoint.FIELD_VISITS.DELETE, data: (data ?? {}) as Record<string, any> }),
  detail: (params?: FieldVisitsDetailParams): Promise<FieldVisitsDetailResponse> => apiService.get<FieldVisitsDetailResponse>({ endpoint: Endpoint.FIELD_VISITS.DETAIL, params: (params ?? {}) as Record<string, any> }),
  export: (params?: FieldVisitsExportParams): Promise<FieldVisitsExportResponse> => apiService.get<FieldVisitsExportResponse>({ endpoint: Endpoint.FIELD_VISITS.EXPORT, params: (params ?? {}) as Record<string, any> }),
  list: (params?: FieldVisitsListParams): Promise<FieldVisitsListResponse> => apiService.get<FieldVisitsListResponse>({ endpoint: Endpoint.FIELD_VISITS.LIST, params: (params ?? {}) as Record<string, any> }),
  create: (data: FieldVisitsCreateParams): Promise<FieldVisitsCreateResponse> => apiService.post<FieldVisitsCreateResponse>({ endpoint: Endpoint.FIELD_VISITS.CREATE, data: (data ?? {}) as Record<string, any> }),
  update: (data: FieldVisitsUpdateParams): Promise<FieldVisitsUpdateResponse> => apiService.put<FieldVisitsUpdateResponse>({ endpoint: Endpoint.FIELD_VISITS.UPDATE, data: (data ?? {}) as Record<string, any> }),
};

export default fieldVisitsService;
