// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/field_visits/
// Wire into a form with: useForm({ resolver: zodResolver(<schema>) }).

import { z } from 'zod';

export const fieldVisitsCreateSchema = z.object({
  farmer_id: z.string({ required_error: 'Farmer is required' }).min(1, 'Farmer is required'),
  farm_id: z.string().optional(),
  visit_date: z.string({ required_error: 'Visit date is required' }).min(1, 'Visit date is required'),
  observations: z.string().optional(),
  pest_sightings: z.string().optional(),
  crop_condition: z.string().optional(),
  soil_observations: z.string().optional(),
  advisories_given: z.string().optional(),
  follow_up_actions: z.string().optional(),
  follow_up_due_date: z.string().optional(),
});
export type FieldVisitsCreateInput = z.infer<typeof fieldVisitsCreateSchema>;

export const fieldVisitsUpdateSchema = z.object({
  observations: z.string().optional(),
  pest_sightings: z.string().optional(),
  crop_condition: z.string().optional(),
  advisories_given: z.string().optional(),
  follow_up_actions: z.string().optional(),
  follow_up_due_date: z.string().optional(),
  status: z.string().optional(),
});
export type FieldVisitsUpdateInput = z.infer<typeof fieldVisitsUpdateSchema>;
