// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/impact/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface ImpactAssessmentListParams {
  page?: number;
  limit?: number;
  programme_id?: string;
  search?: string;
}
export interface ImpactAssessmentListResponse {
  message: string;
  data: Array<{
    id?: string;
    programme_id?: string;
    programme_name?: string;
    methodology?: string;
    status?: string;
    completed_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface ImpactAssessmentResultsParams {
  job_id?: string;
}
export interface ImpactAssessmentResultsResponse {
  message?: string;
  data?: {
    job_id?: string;
    programme_id?: string;
    status?: string;
    yield_improvement_pct?: number;
    income_change_usd?: number;
    adoption_rate_pct?: number;
    resilience_score?: number;
    beneficiaries_assessed?: number;
    methodology?: string;
    results_detail?: Record<string, any>;
    completed_at?: string;
  };
}

export interface ImpactBaselineListParams {
  page?: number;
  limit?: number;
  crop?: string;
  district?: string;
  search?: string;
}
export interface ImpactBaselineListResponse {
  message: string;
  data: Array<{
    id?: string;
    name?: string;
    description?: string;
    crop?: string;
    district?: string;
    year?: number;
    avg_yield_kg_ha?: number;
    avg_income_usd?: number;
    source?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface ImpactAssessmentRunParams {
  programme_id: string;
  baseline_dataset_id: string;
  methodology: string;
  metric_types: Array<string>;
  beneficiary_group_ids: Array<string>;
  comparison_period: string;
}
export interface ImpactAssessmentRunResponse {
  message?: string;
  data?: {
    job_id?: string;
    status?: string;
    estimated_completion?: string;
  };
}

export interface ImpactBeneficiaryLinkParams {
  beneficiary_id: string;
  assessment_id: string;
  pre_intervention_yield: number;
  post_intervention_yield: number;
  pre_intervention_income: number;
  post_intervention_income: number;
  notes: string;
}
export interface ImpactBeneficiaryLinkResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const impactService = {
  assessmentList: (params?: ImpactAssessmentListParams): Promise<ImpactAssessmentListResponse> => apiService.get<ImpactAssessmentListResponse>({ endpoint: Endpoint.IMPACT.ASSESSMENT_LIST, params: (params ?? {}) as Record<string, any> }),
  assessmentResults: (params?: ImpactAssessmentResultsParams): Promise<ImpactAssessmentResultsResponse> => apiService.get<ImpactAssessmentResultsResponse>({ endpoint: Endpoint.IMPACT.ASSESSMENT_RESULTS, params: (params ?? {}) as Record<string, any> }),
  baselineList: (params?: ImpactBaselineListParams): Promise<ImpactBaselineListResponse> => apiService.get<ImpactBaselineListResponse>({ endpoint: Endpoint.IMPACT.BASELINE_LIST, params: (params ?? {}) as Record<string, any> }),
  assessmentRun: (data: ImpactAssessmentRunParams): Promise<ImpactAssessmentRunResponse> => apiService.post<ImpactAssessmentRunResponse>({ endpoint: Endpoint.IMPACT.ASSESSMENT_RUN, data: (data ?? {}) as Record<string, any> }),
  beneficiaryLink: (data: ImpactBeneficiaryLinkParams): Promise<ImpactBeneficiaryLinkResponse> => apiService.post<ImpactBeneficiaryLinkResponse>({ endpoint: Endpoint.IMPACT.BENEFICIARY_LINK, data: (data ?? {}) as Record<string, any> }),
};

export default impactService;
