// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/integrations/
// Wire into a form with: useForm({ resolver: zodResolver(<schema>) }).

import { z } from 'zod';

export const integrationsUpdateSchema = z.object({
  service_name: z.string().optional(),
  api_key: z.string().optional(),
});
export type IntegrationsUpdateInput = z.infer<typeof integrationsUpdateSchema>;
