// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/integrations/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface IntegrationsListParams {
  page?: number;
  limit?: number;
  search?: string;
}
export interface IntegrationsListResponse {
  message: string;
  data: Array<{
    id?: string;
    service_name?: string;
    api_key_masked?: string;
    status?: string;
    last_verified?: string;
    configured_by?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface IntegrationsUpdateParams {
  service_name: string;
  api_key: string;
}
export interface IntegrationsUpdateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const integrationsService = {
  list: (params?: IntegrationsListParams): Promise<IntegrationsListResponse> => apiService.get<IntegrationsListResponse>({ endpoint: Endpoint.INTEGRATIONS.LIST, params: (params ?? {}) as Record<string, any> }),
  update: (data: IntegrationsUpdateParams): Promise<IntegrationsUpdateResponse> => apiService.put<IntegrationsUpdateResponse>({ endpoint: Endpoint.INTEGRATIONS.UPDATE, data: (data ?? {}) as Record<string, any> }),
};

export default integrationsService;
