// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/maps/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface MapsCropZonesParams {
  district?: string;
  page?: number;
  limit?: number;
  search?: string;
}
export interface MapsCropZonesResponse {
  message: string;
  data: Array<{
    district_id?: string;
    district_name?: string;
    crop?: string;
    zone_geojson?: string;
    agro_ecological_zone?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface MapsDistrictProductionParams {
  crop?: string;
  season?: string;
  year?: number;
  page?: number;
  limit?: number;
  search?: string;
}
export interface MapsDistrictProductionResponse {
  message: string;
  data: Array<{
    district_id?: string;
    district_name?: string;
    crop?: string;
    production_volume_mt?: number;
    yield_kg_per_ha?: number;
    geojson?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface MapsDistrictStatsParams {
  district?: string;
  page?: number;
  limit?: number;
  search?: string;
}
export interface MapsDistrictStatsResponse {
  message: string;
  data: Array<{
    district_id?: string;
    district_name?: string;
    total_farmers?: number;
    crop?: string;
    production_volume?: number;
    area_hectares?: number;
    active_alerts?: number;
    season?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface MapsExtensionCoverageParams {
  page?: number;
  limit?: number;
  search?: string;
}
export interface MapsExtensionCoverageResponse {
  message: string;
  data: Array<{
    district_id?: string;
    district_name?: string;
    extension_workers?: number;
    farmers_covered?: number;
    coverage_rate?: number;
    geojson?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface MapsFarmerDensityParams {
  page?: number;
  limit?: number;
  search?: string;
}
export interface MapsFarmerDensityResponse {
  message: string;
  data: Array<{
    district_id?: string;
    district_name?: string;
    farmer_count?: number;
    density_per_km2?: number;
    geojson?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface MapsPestAlertsParams {
  district?: string;
  crop?: string;
  page?: number;
  limit?: number;
  search?: string;
}
export interface MapsPestAlertsResponse {
  message: string;
  data: Array<{
    alert_id?: string;
    district_id?: string;
    district_name?: string;
    pest_name?: string;
    crop?: string;
    severity?: string;
    alert_level?: string;
    issued_at?: string;
    geojson?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface MapsWeatherOverlayParams {
  district?: string;
  page?: number;
  limit?: number;
  search?: string;
}
export interface MapsWeatherOverlayResponse {
  message: string;
  data: Array<{
    district_id?: string;
    district_name?: string;
    temperature?: number;
    rainfall?: number;
    humidity?: number;
    wind_speed?: number;
    condition?: string;
    recorded_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export const mapsService = {
  cropZones: (params?: MapsCropZonesParams): Promise<MapsCropZonesResponse> => apiService.get<MapsCropZonesResponse>({ endpoint: Endpoint.MAPS.CROP_ZONES, params: (params ?? {}) as Record<string, any> }),
  districtProduction: (params?: MapsDistrictProductionParams): Promise<MapsDistrictProductionResponse> => apiService.get<MapsDistrictProductionResponse>({ endpoint: Endpoint.MAPS.DISTRICT_PRODUCTION, params: (params ?? {}) as Record<string, any> }),
  districtStats: (params?: MapsDistrictStatsParams): Promise<MapsDistrictStatsResponse> => apiService.get<MapsDistrictStatsResponse>({ endpoint: Endpoint.MAPS.DISTRICT_STATS, params: (params ?? {}) as Record<string, any> }),
  extensionCoverage: (params?: MapsExtensionCoverageParams): Promise<MapsExtensionCoverageResponse> => apiService.get<MapsExtensionCoverageResponse>({ endpoint: Endpoint.MAPS.EXTENSION_COVERAGE, params: (params ?? {}) as Record<string, any> }),
  farmerDensity: (params?: MapsFarmerDensityParams): Promise<MapsFarmerDensityResponse> => apiService.get<MapsFarmerDensityResponse>({ endpoint: Endpoint.MAPS.FARMER_DENSITY, params: (params ?? {}) as Record<string, any> }),
  pestAlerts: (params?: MapsPestAlertsParams): Promise<MapsPestAlertsResponse> => apiService.get<MapsPestAlertsResponse>({ endpoint: Endpoint.MAPS.PEST_ALERTS, params: (params ?? {}) as Record<string, any> }),
  weatherOverlay: (params?: MapsWeatherOverlayParams): Promise<MapsWeatherOverlayResponse> => apiService.get<MapsWeatherOverlayResponse>({ endpoint: Endpoint.MAPS.WEATHER_OVERLAY, params: (params ?? {}) as Record<string, any> }),
};

export default mapsService;
