// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/market_prices/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface MarketPricesListParams {
  page?: number;
  limit?: number;
  crop?: string;
  market?: string;
  district?: string;
  search?: string;
}
export interface MarketPricesListResponse {
  message: string;
  data: Array<{
    id?: string;
    crop?: string;
    market_name?: string;
    district?: string;
    farm_gate_price?: number;
    market_price?: number;
    export_price?: number;
    unit?: string;
    recorded_date?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface MarketPricesTrendsParams {
  crop?: string;
  district?: string;
  period_days?: number;
}
export interface MarketPricesTrendsResponse {
  message?: string;
  data?: {
    crop?: string;
    district?: string;
    period_days?: number;
    trend_data?: Array<{
      date?: string;
      price?: number;
      market?: string;
    }>;
    price_min?: number;
    price_max?: number;
    price_avg?: number;
    price_change_pct?: number;
  };
}

export const marketPricesService = {
  list: (params?: MarketPricesListParams): Promise<MarketPricesListResponse> => apiService.get<MarketPricesListResponse>({ endpoint: Endpoint.MARKET_PRICES.LIST, params: (params ?? {}) as Record<string, any> }),
  trends: (params?: MarketPricesTrendsParams): Promise<MarketPricesTrendsResponse> => apiService.get<MarketPricesTrendsResponse>({ endpoint: Endpoint.MARKET_PRICES.TRENDS, params: (params ?? {}) as Record<string, any> }),
};

export default marketPricesService;
