// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/monitoring/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface MonitoringProgrammesListParams {
  page?: number;
  limit?: number;
  status?: string;
  search?: string;
}
export interface MonitoringProgrammesListResponse {
  message: string;
  data: Array<{
    id?: string;
    name?: string;
    funder?: string;
    start_date?: string;
    end_date?: string;
    status?: string;
    farmers_targeted?: number;
    farmers_reached?: number;
    disbursed_usd?: number;
    committed_usd?: number;
    districts?: Array<string>;
    crops?: Array<string>;
    milestone_count?: number;
    milestones_achieved?: number;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export type MonitoringStatsParams = Record<string, any>;
export interface MonitoringStatsResponse {
  message?: string;
  data?: {
    total_farmers_covered?: number;
    districts_active?: number;
    crops_targeted?: number;
    total_programmes?: number;
    programmes_on_track?: number;
    programmes_behind_target?: number;
    total_disbursement?: number;
    committed_budget?: number;
  };
}

export const monitoringService = {
  programmesList: (params?: MonitoringProgrammesListParams): Promise<MonitoringProgrammesListResponse> => apiService.get<MonitoringProgrammesListResponse>({ endpoint: Endpoint.MONITORING.PROGRAMMES_LIST, params: (params ?? {}) as Record<string, any> }),
  stats: (params?: MonitoringStatsParams): Promise<MonitoringStatsResponse> => apiService.get<MonitoringStatsResponse>({ endpoint: Endpoint.MONITORING.STATS, params: (params ?? {}) as Record<string, any> }),
};

export default monitoringService;
