// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/national_statistics/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface NationalStatisticsProductionParams {
  crop?: string;
  district?: string;
  agro_ecological_zone?: string;
  season?: string;
  year?: number;
  page?: number;
  limit?: number;
  search?: string;
}
export interface NationalStatisticsProductionResponse {
  message: string;
  data: Array<{
    id?: string;
    crop?: string;
    district?: string;
    agro_ecological_zone?: string;
    season?: string;
    year?: number;
    production_volume_mt?: number;
    area_hectares?: number;
    yield_kg_per_ha?: number;
    source?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface NationalStatisticsTrendsParams {
  crop?: string;
  district?: string;
  from_year?: number;
  to_year?: number;
  page?: number;
  limit?: number;
  search?: string;
}
export interface NationalStatisticsTrendsResponse {
  message: string;
  data: Array<{
    crop?: string;
    district?: string;
    year?: number;
    production_volume_mt?: number;
    yield_kg_per_ha?: number;
    food_security_target_mt?: number;
    target_achievement_pct?: number;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export const nationalStatisticsService = {
  production: (params?: NationalStatisticsProductionParams): Promise<NationalStatisticsProductionResponse> => apiService.get<NationalStatisticsProductionResponse>({ endpoint: Endpoint.NATIONAL_STATISTICS.PRODUCTION, params: (params ?? {}) as Record<string, any> }),
  trends: (params?: NationalStatisticsTrendsParams): Promise<NationalStatisticsTrendsResponse> => apiService.get<NationalStatisticsTrendsResponse>({ endpoint: Endpoint.NATIONAL_STATISTICS.TRENDS, params: (params ?? {}) as Record<string, any> }),
};

export default nationalStatisticsService;
