// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/notifications/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface NotificationsPreferencesParams {
  sms_enabled: boolean;
  email_enabled: boolean;
  in_app_enabled: boolean;
  phone_number: string;
  email: string;
  alert_types: Array<string>;
}
export interface NotificationsPreferencesResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const notificationsService = {
  preferences: (data: NotificationsPreferencesParams): Promise<NotificationsPreferencesResponse> => apiService.put<NotificationsPreferencesResponse>({ endpoint: Endpoint.NOTIFICATIONS.PREFERENCES, data: (data ?? {}) as Record<string, any> }),
};

export default notificationsService;
