// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/pest_sightings/
// Wire into a form with: useForm({ resolver: zodResolver(<schema>) }).

import { z } from 'zod';

export const pestSightingsCreateSchema = z.object({
  farm_id: z.string({ required_error: 'Farm is required' }).min(1, 'Farm is required'),
  pest_id: z.string({ required_error: 'Pest is required' }).min(1, 'Pest is required'),
  sighting_date: z.string({ required_error: 'Sighting date is required' }).min(1, 'Sighting date is required'),
  crop_affected: z.string().optional(),
  severity_estimate: z.string().optional(),
  area_affected_hectares: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  notes: z.string().optional(),
  gps_lat: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  gps_lng: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
});
export type PestSightingsCreateInput = z.infer<typeof pestSightingsCreateSchema>;

export const pestSightingsUpdateSchema = z.object({
  sighting_date: z.string().optional(),
  severity_estimate: z.string().optional(),
  area_affected_hectares: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  notes: z.string().optional(),
});
export type PestSightingsUpdateInput = z.infer<typeof pestSightingsUpdateSchema>;
