// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/pest_alerts/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface PestAlertsListParams {
  page?: number;
  limit?: number;
  district?: string;
  crop?: string;
  alert_level?: string;
  search?: string;
}
export interface PestAlertsListResponse {
  message: string;
  data: Array<{
    id?: string;
    pest_name?: string;
    type?: string;
    crop?: string;
    alert_level?: string;
    description?: string;
    scouting_action?: string;
    treatment_options?: string;
    triggered_by?: string;
    district?: string;
    issued_at?: string;
    forecast_days_ahead?: number;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export const pestAlertsService = {
  list: (params?: PestAlertsListParams): Promise<PestAlertsListResponse> => apiService.get<PestAlertsListResponse>({ endpoint: Endpoint.PEST_ALERTS.LIST, params: (params ?? {}) as Record<string, any> }),
};

export default pestAlertsService;
