// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/pest_sightings/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface PestSightingsDeleteParams {
  id: string;
}
export interface PestSightingsDeleteResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface PestSightingsDetailParams {
  id?: string;
}
export interface PestSightingsDetailResponse {
  message?: string;
  data?: {
    id?: string;
    farm_id?: string;
    pest_name?: string;
    crop_affected?: string;
    sighting_date?: string;
    severity_estimate?: string;
    area_affected_hectares?: number;
    notes?: string;
    gps_lat?: number;
    gps_lng?: number;
    created_at?: string;
    updated_at?: string;
  };
}

export interface PestSightingsListParams {
  farm_id?: string;
  page?: number;
  limit?: number;
  search?: string;
}
export interface PestSightingsListResponse {
  message: string;
  data: Array<{
    id?: string;
    farm_id?: string;
    pest_name?: string;
    crop_affected?: string;
    sighting_date?: string;
    severity_estimate?: string;
    area_affected_hectares?: number;
    notes?: string;
    gps_lat?: number;
    gps_lng?: number;
    created_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface PestSightingsCreateParams {
  farm_id: string;
  pest_id: string;
  sighting_date: string;
  crop_affected: string;
  severity_estimate: string;
  area_affected_hectares: number;
  notes: string;
  gps_lat: number;
  gps_lng: number;
}
export interface PestSightingsCreateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface PestSightingsUpdateParams {
  id: string;
  sighting_date: string;
  severity_estimate: string;
  area_affected_hectares: number;
  notes: string;
}
export interface PestSightingsUpdateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const pestSightingsService = {
  delete: (data: PestSightingsDeleteParams): Promise<PestSightingsDeleteResponse> => apiService.delete<PestSightingsDeleteResponse>({ endpoint: Endpoint.PEST_SIGHTINGS.DELETE, data: (data ?? {}) as Record<string, any> }),
  detail: (params?: PestSightingsDetailParams): Promise<PestSightingsDetailResponse> => apiService.get<PestSightingsDetailResponse>({ endpoint: Endpoint.PEST_SIGHTINGS.DETAIL, params: (params ?? {}) as Record<string, any> }),
  list: (params?: PestSightingsListParams): Promise<PestSightingsListResponse> => apiService.get<PestSightingsListResponse>({ endpoint: Endpoint.PEST_SIGHTINGS.LIST, params: (params ?? {}) as Record<string, any> }),
  create: (data: PestSightingsCreateParams): Promise<PestSightingsCreateResponse> => apiService.post<PestSightingsCreateResponse>({ endpoint: Endpoint.PEST_SIGHTINGS.CREATE, data: (data ?? {}) as Record<string, any> }),
  update: (data: PestSightingsUpdateParams): Promise<PestSightingsUpdateResponse> => apiService.put<PestSightingsUpdateResponse>({ endpoint: Endpoint.PEST_SIGHTINGS.UPDATE, data: (data ?? {}) as Record<string, any> }),
};

export default pestSightingsService;
