// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/pests/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface PestsListParams {
  page?: number;
  limit?: number;
  crop?: string;
  type?: string;
  search?: string;
}
export interface PestsListResponse {
  message: string;
  data: Array<{
    id?: string;
    name?: string;
    type?: string;
    affected_crops?: Array<string>;
    climate_trigger?: string;
    severity?: string;
    description?: string;
    recommended_actions?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export const pestsService = {
  list: (params?: PestsListParams): Promise<PestsListResponse> => apiService.get<PestsListResponse>({ endpoint: Endpoint.PESTS.LIST, params: (params ?? {}) as Record<string, any> }),
};

export default pestsService;
