// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/pest_reports/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface PestReportsListParams {
  page?: number;
  limit?: number;
  crop?: string;
  district?: string;
  season?: string;
  alert_level?: string;
  search?: string;
}
export interface PestReportsListResponse {
  message: string;
  data: Array<{
    id?: string;
    pest_name?: string;
    crop?: string;
    district?: string;
    alert_level?: string;
    outbreak_date?: string;
    response_status?: string;
    coverage_gap?: boolean;
    season?: string;
    created_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface PestReportsTrendsParams {
  crop?: string;
  district?: string;
  pest_name?: string;
  from_season?: string;
  to_season?: string;
  page?: number;
  limit?: number;
  search?: string;
}
export interface PestReportsTrendsResponse {
  message: string;
  data: Array<{
    season?: string;
    crop?: string;
    pest_name?: string;
    outbreak_count?: number;
    districts_affected?: number;
    response_rate?: number;
    avg_response_days?: number;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface PestReportsGenerateParams {
  crop_ids: Array<string>;
  district_ids: Array<string>;
  from_date: string;
  to_date: string;
  include_famews_format: boolean;
  output_format: string;
}
export interface PestReportsGenerateResponse {
  message?: string;
  data?: {
    report_id?: string;
    download_url?: string;
    generated_at?: string;
  };
}

export const pestReportsService = {
  list: (params?: PestReportsListParams): Promise<PestReportsListResponse> => apiService.get<PestReportsListResponse>({ endpoint: Endpoint.PEST_REPORTS.LIST, params: (params ?? {}) as Record<string, any> }),
  trends: (params?: PestReportsTrendsParams): Promise<PestReportsTrendsResponse> => apiService.get<PestReportsTrendsResponse>({ endpoint: Endpoint.PEST_REPORTS.TRENDS, params: (params ?? {}) as Record<string, any> }),
  generate: (data: PestReportsGenerateParams): Promise<PestReportsGenerateResponse> => apiService.post<PestReportsGenerateResponse>({ endpoint: Endpoint.PEST_REPORTS.GENERATE, data: (data ?? {}) as Record<string, any> }),
};

export default pestReportsService;
