// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/policy/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export type PolicyAlertsSummaryParams = Record<string, any>;
export interface PolicyAlertsSummaryResponse {
  message?: string;
  data?: {
    total_active_alerts?: number;
    emergency?: number;
    warning?: number;
    watch?: number;
    by_crop?: Array<{
      crop?: string;
      count?: number;
    }>;
    by_district?: Array<{
      district?: string;
      count?: number;
      highest_severity?: string;
    }>;
  };
}

export interface PolicyDistrictMapParams {
  page?: number;
  limit?: number;
  search?: string;
}
export interface PolicyDistrictMapResponse {
  message: string;
  data: Array<{
    district_id?: string;
    district_name?: string;
    production_volume?: number;
    active_alerts?: number;
    farmer_count?: number;
    advisory_coverage_rate?: number;
    agro_ecological_zone?: string;
    geojson?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface PolicySeasonTrendsParams {
  crop?: string;
  season?: string;
  page?: number;
  limit?: number;
  search?: string;
}
export interface PolicySeasonTrendsResponse {
  message: string;
  data: Array<{
    crop?: string;
    season?: string;
    current_production_mt?: number;
    five_year_avg_mt?: number;
    variance_pct?: number;
    year?: number;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export type PolicyStatsParams = Record<string, any>;
export interface PolicyStatsResponse {
  message?: string;
  data?: {
    total_national_production_mt?: number;
    active_pest_alerts?: number;
    extension_advisory_coverage_rate?: number;
    districts_with_alerts?: number;
    season?: string;
    benchmark_achievement_pct?: number;
  };
}

export const policyService = {
  alertsSummary: (params?: PolicyAlertsSummaryParams): Promise<PolicyAlertsSummaryResponse> => apiService.get<PolicyAlertsSummaryResponse>({ endpoint: Endpoint.POLICY.ALERTS_SUMMARY, params: (params ?? {}) as Record<string, any> }),
  districtMap: (params?: PolicyDistrictMapParams): Promise<PolicyDistrictMapResponse> => apiService.get<PolicyDistrictMapResponse>({ endpoint: Endpoint.POLICY.DISTRICT_MAP, params: (params ?? {}) as Record<string, any> }),
  seasonTrends: (params?: PolicySeasonTrendsParams): Promise<PolicySeasonTrendsResponse> => apiService.get<PolicySeasonTrendsResponse>({ endpoint: Endpoint.POLICY.SEASON_TRENDS, params: (params ?? {}) as Record<string, any> }),
  stats: (params?: PolicyStatsParams): Promise<PolicyStatsResponse> => apiService.get<PolicyStatsResponse>({ endpoint: Endpoint.POLICY.STATS, params: (params ?? {}) as Record<string, any> }),
};

export default policyService;
