// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/price_alerts/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface PriceAlertsDeleteParams {
  id: string;
}
export interface PriceAlertsDeleteResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface PriceAlertsDetailParams {
  id?: string;
}
export interface PriceAlertsDetailResponse {
  message?: string;
  data?: {
    id?: string;
    crop?: string;
    target_price?: number;
    market?: string;
    current_price?: number;
    sms_enabled?: boolean;
    email_enabled?: boolean;
    triggered?: boolean;
    created_at?: string;
    updated_at?: string;
  };
}

export interface PriceAlertsListParams {
  page?: number;
  limit?: number;
  search?: string;
}
export interface PriceAlertsListResponse {
  message: string;
  data: Array<{
    id?: string;
    crop?: string;
    target_price?: number;
    market?: string;
    current_price?: number;
    sms_enabled?: boolean;
    email_enabled?: boolean;
    triggered?: boolean;
    created_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface PriceAlertsCreateParams {
  crop_id: string;
  target_price: number;
  market: string;
  sms_enabled: boolean;
  email_enabled: boolean;
}
export interface PriceAlertsCreateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface PriceAlertsUpdateParams {
  id: string;
  crop_id: string;
  target_price: number;
  market: string;
  sms_enabled: boolean;
  email_enabled: boolean;
}
export interface PriceAlertsUpdateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const priceAlertsService = {
  delete: (data: PriceAlertsDeleteParams): Promise<PriceAlertsDeleteResponse> => apiService.delete<PriceAlertsDeleteResponse>({ endpoint: Endpoint.PRICE_ALERTS.DELETE, data: (data ?? {}) as Record<string, any> }),
  detail: (params?: PriceAlertsDetailParams): Promise<PriceAlertsDetailResponse> => apiService.get<PriceAlertsDetailResponse>({ endpoint: Endpoint.PRICE_ALERTS.DETAIL, params: (params ?? {}) as Record<string, any> }),
  list: (params?: PriceAlertsListParams): Promise<PriceAlertsListResponse> => apiService.get<PriceAlertsListResponse>({ endpoint: Endpoint.PRICE_ALERTS.LIST, params: (params ?? {}) as Record<string, any> }),
  create: (data: PriceAlertsCreateParams): Promise<PriceAlertsCreateResponse> => apiService.post<PriceAlertsCreateResponse>({ endpoint: Endpoint.PRICE_ALERTS.CREATE, data: (data ?? {}) as Record<string, any> }),
  update: (data: PriceAlertsUpdateParams): Promise<PriceAlertsUpdateResponse> => apiService.put<PriceAlertsUpdateResponse>({ endpoint: Endpoint.PRICE_ALERTS.UPDATE, data: (data ?? {}) as Record<string, any> }),
};

export default priceAlertsService;
