// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/price_alerts/
// Wire into a form with: useForm({ resolver: zodResolver(<schema>) }).

import { z } from 'zod';

export const priceAlertsCreateSchema = z.object({
  crop_id: z.string({ required_error: 'Crop is required' }).min(1, 'Crop is required'),
  target_price: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number({ invalid_type_error: 'Target price is required' })),
  market: z.string().optional(),
  sms_enabled: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  email_enabled: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
});
export type PriceAlertsCreateInput = z.infer<typeof priceAlertsCreateSchema>;

export const priceAlertsUpdateSchema = z.object({
  crop_id: z.string().optional(),
  target_price: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  market: z.string().optional(),
  sms_enabled: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  email_enabled: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
});
export type PriceAlertsUpdateInput = z.infer<typeof priceAlertsUpdateSchema>;
