// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/production_reports/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface ProductionReportsListParams {
  page?: number;
  limit?: number;
  report_type?: string;
  search?: string;
}
export interface ProductionReportsListResponse {
  message: string;
  data: Array<{
    id?: string;
    name?: string;
    report_type?: string;
    parameters?: Record<string, any>;
    output_format?: string;
    download_url?: string;
    generated_at?: string;
    generated_by?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface ProductionReportsTemplatesParams {
  page?: number;
  limit?: number;
  search?: string;
}
export interface ProductionReportsTemplatesResponse {
  message: string;
  data: Array<{
    id?: string;
    name?: string;
    description?: string;
    report_type?: string;
    parameters?: Array<string>;
    output_formats?: Array<string>;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface ProductionReportsGenerateParams {
  template_id: string;
  crop_ids: Array<string>;
  district_ids: Array<string>;
  from_date: string;
  to_date: string;
  season: string;
  comparison_baseline: string;
  output_format: string;
}
export interface ProductionReportsGenerateResponse {
  message?: string;
  data?: {
    report_id?: string;
    status?: string;
    download_url?: string;
    generated_at?: string;
  };
}

export interface ProductionReportsScheduleParams {
  template_id: string;
  crop_ids: Array<string>;
  district_ids: Array<string>;
  frequency: string;
  next_run_date: string;
  output_format: string;
  recipient_emails: Array<string>;
}
export interface ProductionReportsScheduleResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const productionReportsService = {
  list: (params?: ProductionReportsListParams): Promise<ProductionReportsListResponse> => apiService.get<ProductionReportsListResponse>({ endpoint: Endpoint.PRODUCTION_REPORTS.LIST, params: (params ?? {}) as Record<string, any> }),
  templates: (params?: ProductionReportsTemplatesParams): Promise<ProductionReportsTemplatesResponse> => apiService.get<ProductionReportsTemplatesResponse>({ endpoint: Endpoint.PRODUCTION_REPORTS.TEMPLATES, params: (params ?? {}) as Record<string, any> }),
  generate: (data: ProductionReportsGenerateParams): Promise<ProductionReportsGenerateResponse> => apiService.post<ProductionReportsGenerateResponse>({ endpoint: Endpoint.PRODUCTION_REPORTS.GENERATE, data: (data ?? {}) as Record<string, any> }),
  schedule: (data: ProductionReportsScheduleParams): Promise<ProductionReportsScheduleResponse> => apiService.post<ProductionReportsScheduleResponse>({ endpoint: Endpoint.PRODUCTION_REPORTS.SCHEDULE, data: (data ?? {}) as Record<string, any> }),
};

export default productionReportsService;
