// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/programme_kpis/
// Wire into a form with: useForm({ resolver: zodResolver(<schema>) }).

import { z } from 'zod';

export const programmeKpisCreateSchema = z.object({
  programme_id: z.string({ required_error: 'Programme is required' }).min(1, 'Programme is required'),
  kpi_name: z.string({ required_error: 'Kpi name is required' }).min(1, 'Kpi name is required'),
  kpi_category: z.string().optional(),
  target_value: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  unit: z.string().optional(),
  threshold_alert: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  email_alert_enabled: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
});
export type ProgrammeKpisCreateInput = z.infer<typeof programmeKpisCreateSchema>;

export const programmeKpisUpdateSchema = z.object({
  kpi_name: z.string().optional(),
  target_value: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  unit: z.string().optional(),
  threshold_alert: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
  email_alert_enabled: z.preprocess((v) => (v === '' || v === null || v === undefined ? undefined : v), z.coerce.number().optional()),
});
export type ProgrammeKpisUpdateInput = z.infer<typeof programmeKpisUpdateSchema>;
