// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/programme_kpis/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface ProgrammeKpisDeleteParams {
  id: string;
}
export interface ProgrammeKpisDeleteResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface ProgrammeKpisDetailParams {
  id?: string;
}
export interface ProgrammeKpisDetailResponse {
  message?: string;
  data?: {
    id?: string;
    programme_id?: string;
    kpi_name?: string;
    kpi_category?: string;
    target_value?: number;
    current_value?: number;
    unit?: string;
    achievement_pct?: number;
    threshold_alert?: number;
    email_alert_enabled?: boolean;
    status?: string;
    history?: Array<{
      date?: string;
      value?: number;
    }>;
    last_updated?: string;
  };
}

export interface ProgrammeKpisListParams {
  page?: number;
  limit?: number;
  programme_id?: string;
  status?: string;
  search?: string;
}
export interface ProgrammeKpisListResponse {
  message: string;
  data: Array<{
    id?: string;
    programme_id?: string;
    kpi_name?: string;
    kpi_category?: string;
    target_value?: number;
    current_value?: number;
    unit?: string;
    achievement_pct?: number;
    threshold_alert?: number;
    status?: string;
    last_updated?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface ProgrammeKpisCreateParams {
  programme_id: string;
  kpi_name: string;
  kpi_category: string;
  target_value: number;
  unit: string;
  threshold_alert: number;
  email_alert_enabled: boolean;
}
export interface ProgrammeKpisCreateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface ProgrammeKpisUpdateParams {
  id: string;
  kpi_name: string;
  target_value: number;
  unit: string;
  threshold_alert: number;
  email_alert_enabled: boolean;
}
export interface ProgrammeKpisUpdateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const programmeKpisService = {
  delete: (data: ProgrammeKpisDeleteParams): Promise<ProgrammeKpisDeleteResponse> => apiService.delete<ProgrammeKpisDeleteResponse>({ endpoint: Endpoint.PROGRAMME_KPIS.DELETE, data: (data ?? {}) as Record<string, any> }),
  detail: (params?: ProgrammeKpisDetailParams): Promise<ProgrammeKpisDetailResponse> => apiService.get<ProgrammeKpisDetailResponse>({ endpoint: Endpoint.PROGRAMME_KPIS.DETAIL, params: (params ?? {}) as Record<string, any> }),
  list: (params?: ProgrammeKpisListParams): Promise<ProgrammeKpisListResponse> => apiService.get<ProgrammeKpisListResponse>({ endpoint: Endpoint.PROGRAMME_KPIS.LIST, params: (params ?? {}) as Record<string, any> }),
  create: (data: ProgrammeKpisCreateParams): Promise<ProgrammeKpisCreateResponse> => apiService.post<ProgrammeKpisCreateResponse>({ endpoint: Endpoint.PROGRAMME_KPIS.CREATE, data: (data ?? {}) as Record<string, any> }),
  update: (data: ProgrammeKpisUpdateParams): Promise<ProgrammeKpisUpdateResponse> => apiService.put<ProgrammeKpisUpdateResponse>({ endpoint: Endpoint.PROGRAMME_KPIS.UPDATE, data: (data ?? {}) as Record<string, any> }),
};

export default programmeKpisService;
