// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/public_reports/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface PublicReportsListParams {
  page?: number;
  limit?: number;
  category?: string;
  crop?: string;
  season?: string;
  from_date?: string;
  to_date?: string;
  search?: string;
}
export interface PublicReportsListResponse {
  message: string;
  data: Array<{
    id?: string;
    title?: string;
    category?: string;
    crop?: Array<string>;
    season?: string;
    publisher?: string;
    published_date?: string;
    description?: string;
    download_url?: string;
    file_size_kb?: number;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export const publicReportsService = {
  list: (params?: PublicReportsListParams): Promise<PublicReportsListResponse> => apiService.get<PublicReportsListResponse>({ endpoint: Endpoint.PUBLIC_REPORTS.LIST, params: (params ?? {}) as Record<string, any> }),
};

export default publicReportsService;
