// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/recommendations/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface RecommendationsEarlyWarningsParams {
  crop?: string;
  district?: string;
  days_ahead?: number;
  page?: number;
  limit?: number;
  search?: string;
}
export interface RecommendationsEarlyWarningsResponse {
  message: string;
  data: Array<{
    id?: string;
    crop?: string;
    warning_type?: string;
    title?: string;
    description?: string;
    forecast_date?: string;
    confidence_score?: number;
    triggering_forecast?: string;
    recommended_action?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface RecommendationsListParams {
  page?: number;
  limit?: number;
  crop?: string;
  farm_id?: string;
  search?: string;
}
export interface RecommendationsListResponse {
  message: string;
  data: Array<{
    id?: string;
    crop?: string;
    recommendation_type?: string;
    title?: string;
    description?: string;
    confidence_score?: number;
    triggering_conditions?: string;
    guideline_reference?: string;
    valid_from?: string;
    valid_until?: string;
    created_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export const recommendationsService = {
  earlyWarnings: (params?: RecommendationsEarlyWarningsParams): Promise<RecommendationsEarlyWarningsResponse> => apiService.get<RecommendationsEarlyWarningsResponse>({ endpoint: Endpoint.RECOMMENDATIONS.EARLY_WARNINGS, params: (params ?? {}) as Record<string, any> }),
  list: (params?: RecommendationsListParams): Promise<RecommendationsListResponse> => apiService.get<RecommendationsListResponse>({ endpoint: Endpoint.RECOMMENDATIONS.LIST, params: (params ?? {}) as Record<string, any> }),
};

export default recommendationsService;
