// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/reports/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface ReportsAlertsHistoryParams {
  district?: string;
  season?: string;
  crop?: string;
  from_date?: string;
  to_date?: string;
}
export interface ReportsAlertsHistoryResponse {
  message?: string;
  data?: {
    district?: string;
    season?: string;
    total_alerts?: number;
    alerts_with_advisory?: number;
    advisory_coverage_rate?: number;
    farmer_compliance_rate?: number;
    alert_breakdown?: Array<{
      alert_type?: string;
      count?: number;
      crop?: string;
    }>;
  };
}

export const reportsService = {
  alertsHistory: (params?: ReportsAlertsHistoryParams): Promise<ReportsAlertsHistoryResponse> => apiService.get<ReportsAlertsHistoryResponse>({ endpoint: Endpoint.REPORTS.ALERTS_HISTORY, params: (params ?? {}) as Record<string, any> }),
};

export default reportsService;
