// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/research_outputs/
// Wire into a form with: useForm({ resolver: zodResolver(<schema>) }).

import { z } from 'zod';

export const researchOutputsCreateSchema = z.object({
  title: z.string({ required_error: 'Title is required' }).min(1, 'Title is required'),
  authors: z.array(z.string()).optional(),
  abstract: z.string().optional(),
  crop_focus_ids: z.array(z.string()).optional(),
  dataset_ids: z.array(z.string()).optional(),
  model_ids: z.array(z.string()).optional(),
  methodology: z.string().optional(),
  key_findings: z.string().optional(),
  file: z.string({ required_error: 'File is required' }).min(1, 'File is required'),
});
export type ResearchOutputsCreateInput = z.infer<typeof researchOutputsCreateSchema>;

export const researchOutputsUpdateSchema = z.object({
  title: z.string().optional(),
  authors: z.array(z.string()).optional(),
  abstract: z.string().optional(),
  crop_focus_ids: z.array(z.string()).optional(),
  dataset_ids: z.array(z.string()).optional(),
  model_ids: z.array(z.string()).optional(),
  methodology: z.string().optional(),
  key_findings: z.string().optional(),
  status: z.string().optional(),
});
export type ResearchOutputsUpdateInput = z.infer<typeof researchOutputsUpdateSchema>;
