// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/research_outputs/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface ResearchOutputsDeleteParams {
  id: string;
}
export interface ResearchOutputsDeleteResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface ResearchOutputsDetailParams {
  id?: string;
}
export interface ResearchOutputsDetailResponse {
  message?: string;
  data?: {
    id?: string;
    title?: string;
    authors?: Array<string>;
    abstract?: string;
    crop_focus?: Array<string>;
    status?: string;
    datasets_used?: Array<{
      id?: string;
      name?: string;
    }>;
    models_applied?: Array<{
      id?: string;
      name?: string;
    }>;
    methodology?: string;
    key_findings?: string;
    citation?: string;
    file_url?: string;
    version_history?: Array<{
      version?: number;
      updated_at?: string;
      changes?: string;
    }>;
    published_at?: string;
    created_at?: string;
    updated_at?: string;
  };
}

export interface ResearchOutputsListParams {
  page?: number;
  limit?: number;
  crop?: string;
  status?: string;
  search?: string;
  author?: string;
}
export interface ResearchOutputsListResponse {
  message: string;
  data: Array<{
    id?: string;
    title?: string;
    authors?: Array<string>;
    abstract?: string;
    crop_focus?: Array<string>;
    status?: string;
    datasets_used?: Array<string>;
    models_applied?: Array<string>;
    published_at?: string;
    created_at?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface ResearchOutputsCreateParams {
  title: string;
  authors: string;
  abstract: string;
  crop_focus_ids: string;
  dataset_ids: string;
  model_ids: string;
  methodology: string;
  key_findings: string;
  file: string;
}
export interface ResearchOutputsCreateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export interface ResearchOutputsUpdateParams {
  id: string;
  title: string;
  authors: Array<string>;
  abstract: string;
  crop_focus_ids: Array<string>;
  dataset_ids: Array<string>;
  model_ids: Array<string>;
  methodology: string;
  key_findings: string;
  status: string;
}
export interface ResearchOutputsUpdateResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const researchOutputsService = {
  delete: (data: ResearchOutputsDeleteParams): Promise<ResearchOutputsDeleteResponse> => apiService.delete<ResearchOutputsDeleteResponse>({ endpoint: Endpoint.RESEARCH_OUTPUTS.DELETE, data: (data ?? {}) as Record<string, any> }),
  detail: (params?: ResearchOutputsDetailParams): Promise<ResearchOutputsDetailResponse> => apiService.get<ResearchOutputsDetailResponse>({ endpoint: Endpoint.RESEARCH_OUTPUTS.DETAIL, params: (params ?? {}) as Record<string, any> }),
  list: (params?: ResearchOutputsListParams): Promise<ResearchOutputsListResponse> => apiService.get<ResearchOutputsListResponse>({ endpoint: Endpoint.RESEARCH_OUTPUTS.LIST, params: (params ?? {}) as Record<string, any> }),
  create: (data: ResearchOutputsCreateParams): Promise<ResearchOutputsCreateResponse> => apiService.post<ResearchOutputsCreateResponse>({ endpoint: Endpoint.RESEARCH_OUTPUTS.CREATE, data: (data ?? {}) as Record<string, any> }),
  update: (data: ResearchOutputsUpdateParams): Promise<ResearchOutputsUpdateResponse> => apiService.put<ResearchOutputsUpdateResponse>({ endpoint: Endpoint.RESEARCH_OUTPUTS.UPDATE, data: (data ?? {}) as Record<string, any> }),
};

export default researchOutputsService;
