// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/seasonal_calendars/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface SeasonalCalendarsListParams {
  crop?: string;
  season?: string;
  agro_ecological_zone?: string;
  page?: number;
  limit?: number;
  search?: string;
}
export interface SeasonalCalendarsListResponse {
  message: string;
  data: Array<{
    id?: string;
    crop?: string;
    season?: string;
    season_months?: string;
    planting_start?: string;
    planting_end?: string;
    growing_start?: string;
    growing_end?: string;
    harvest_start?: string;
    harvest_end?: string;
    agro_ecological_zone?: string;
    notes?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface SeasonalCalendarsPestRiskWindowsParams {
  crop?: string;
  season?: string;
  agro_ecological_zone?: string;
  page?: number;
  limit?: number;
  search?: string;
}
export interface SeasonalCalendarsPestRiskWindowsResponse {
  message: string;
  data: Array<{
    id?: string;
    crop?: string;
    pest_name?: string;
    risk_start_month?: string;
    risk_end_month?: string;
    risk_level?: string;
    season?: string;
    agro_ecological_zone?: string;
    trigger_conditions?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export const seasonalCalendarsService = {
  list: (params?: SeasonalCalendarsListParams): Promise<SeasonalCalendarsListResponse> => apiService.get<SeasonalCalendarsListResponse>({ endpoint: Endpoint.SEASONAL_CALENDARS.LIST, params: (params ?? {}) as Record<string, any> }),
  pestRiskWindows: (params?: SeasonalCalendarsPestRiskWindowsParams): Promise<SeasonalCalendarsPestRiskWindowsResponse> => apiService.get<SeasonalCalendarsPestRiskWindowsResponse>({ endpoint: Endpoint.SEASONAL_CALENDARS.PEST_RISK_WINDOWS, params: (params ?? {}) as Record<string, any> }),
};

export default seasonalCalendarsService;
