// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/statistical_analysis/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface StatisticalAnalysisResultsParams {
  job_id?: string;
}
export interface StatisticalAnalysisResultsResponse {
  message?: string;
  data?: {
    job_id?: string;
    analysis_method?: string;
    status?: string;
    summary_statistics?: Record<string, any>;
    correlation_matrix?: Record<string, any>;
    trend_data?: Record<string, any>;
    charts?: Array<{
      title?: string;
      type?: string;
      data?: Record<string, any>;
    }>;
    export_url_csv?: string;
    export_url_pdf?: string;
    completed_at?: string;
  };
}

export interface StatisticalAnalysisRunParams {
  dataset_ids: Array<string>;
  analysis_method: string;
  variables: Array<string>;
  filters: Record<string, any>;
  season: string;
  district: string;
}
export interface StatisticalAnalysisRunResponse {
  message?: string;
  data?: {
    job_id?: string;
    status?: string;
    estimated_completion?: string;
  };
}

export const statisticalAnalysisService = {
  results: (params?: StatisticalAnalysisResultsParams): Promise<StatisticalAnalysisResultsResponse> => apiService.get<StatisticalAnalysisResultsResponse>({ endpoint: Endpoint.STATISTICAL_ANALYSIS.RESULTS, params: (params ?? {}) as Record<string, any> }),
  run: (data: StatisticalAnalysisRunParams): Promise<StatisticalAnalysisRunResponse> => apiService.post<StatisticalAnalysisRunResponse>({ endpoint: Endpoint.STATISTICAL_ANALYSIS.RUN, data: (data ?? {}) as Record<string, any> }),
};

export default statisticalAnalysisService;
