// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/treatments/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface TreatmentsListParams {
  pest_id?: string;
  crop?: string;
  page?: number;
  limit?: number;
  search?: string;
}
export interface TreatmentsListResponse {
  message: string;
  data: Array<{
    id?: string;
    pest_name?: string;
    crop?: string;
    scouting_action?: string;
    chemical_treatment?: string;
    biological_treatment?: string;
    cultural_practice?: string;
    maaif_approved?: boolean;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export const treatmentsService = {
  list: (params?: TreatmentsListParams): Promise<TreatmentsListResponse> => apiService.get<TreatmentsListResponse>({ endpoint: Endpoint.TREATMENTS.LIST, params: (params ?? {}) as Record<string, any> }),
};

export default treatmentsService;
