// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/users/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export type UsersProfileParams = Record<string, any>;
export interface UsersProfileResponse {
  message?: string;
  data?: {
    id?: string;
    full_name?: string;
    email?: string;
    phone_number?: string;
    role?: string;
    district?: string;
    sub_county?: string;
    sms_enabled?: boolean;
    email_notifications_enabled?: boolean;
    in_app_enabled?: boolean;
    created_at?: string;
    updated_at?: string;
  };
}

export interface UsersPutProfileParams {
  full_name: string;
  email: string;
  phone_number: string;
  district_id: string;
  sub_county: string;
  current_password: string;
  new_password: string;
}
export interface UsersPutProfileResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const usersService = {
  profile: (params?: UsersProfileParams): Promise<UsersProfileResponse> => apiService.get<UsersProfileResponse>({ endpoint: Endpoint.USERS.PROFILE, params: (params ?? {}) as Record<string, any> }),
  putProfile: (data: UsersPutProfileParams): Promise<UsersPutProfileResponse> => apiService.put<UsersPutProfileResponse>({ endpoint: Endpoint.USERS.PUT_PROFILE, data: (data ?? {}) as Record<string, any> }),
};

export default usersService;
