// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/varieties/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface VarietiesListParams {
  page?: number;
  limit?: number;
  crop?: string;
  search?: string;
}
export interface VarietiesListResponse {
  message: string;
  data: Array<{
    id?: string;
    variety_name?: string;
    crop?: string;
    yield_improvement_kg_ha?: number;
    drought_tolerant?: boolean;
    pest_resistant?: boolean;
    maturity_days?: number;
    developer?: string;
    description?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export const varietiesService = {
  list: (params?: VarietiesListParams): Promise<VarietiesListResponse> => apiService.get<VarietiesListResponse>({ endpoint: Endpoint.VARIETIES.LIST, params: (params ?? {}) as Record<string, any> }),
};

export default varietiesService;
