// AUTO-GENERATED by mock-codegen — do not edit.
// Source: /planner/api_details/weather/

import apiService from './apiService';
import { Endpoint } from './endpoints';

export interface WeatherCurrentParams {
  district?: string;
}
export interface WeatherCurrentResponse {
  message?: string;
  data?: {
    district?: string;
    temperature?: number;
    rainfall?: number;
    humidity?: number;
    wind_speed?: number;
    condition?: string;
    anomaly_flag?: boolean;
    season_position?: string;
    recorded_at?: string;
  };
}

export interface WeatherExportParams {
  district?: string;
  from_date?: string;
  to_date?: string;
  format?: string;
  variables?: string;
}
export interface WeatherExportResponse {
  message?: string;
  data?: {
    download_url?: string;
    file_name?: string;
    record_count?: number;
    generated_at?: string;
  };
}

export interface WeatherForecastParams {
  district?: string;
  page?: number;
  limit?: number;
  search?: string;
}
export interface WeatherForecastResponse {
  message: string;
  data: Array<{
    date?: string;
    temperature_min?: number;
    temperature_max?: number;
    rainfall?: number;
    humidity?: number;
    wind_speed?: number;
    condition?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface WeatherHistoricalParams {
  district?: string;
  agro_ecological_zone?: string;
  from_date?: string;
  to_date?: string;
  season?: string;
  variable?: string;
  page?: number;
  limit?: number;
  search?: string;
}
export interface WeatherHistoricalResponse {
  message: string;
  data: Array<{
    date?: string;
    district?: string;
    agro_ecological_zone?: string;
    temperature?: number;
    rainfall?: number;
    humidity?: number;
    wind_speed?: number;
    season?: string;
  }>;
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface WeatherExportScheduleParams {
  district: string;
  variables: Array<string>;
  format: string;
  frequency: string;
  destination_url: string;
  start_date: string;
}
export interface WeatherExportScheduleResponse {
  message?: string;
  data?: {
    id?: string;
  };
}

export const weatherService = {
  current: (params?: WeatherCurrentParams): Promise<WeatherCurrentResponse> => apiService.get<WeatherCurrentResponse>({ endpoint: Endpoint.WEATHER.CURRENT, params: (params ?? {}) as Record<string, any> }),
  export: (params?: WeatherExportParams): Promise<WeatherExportResponse> => apiService.get<WeatherExportResponse>({ endpoint: Endpoint.WEATHER.EXPORT, params: (params ?? {}) as Record<string, any> }),
  forecast: (params?: WeatherForecastParams): Promise<WeatherForecastResponse> => apiService.get<WeatherForecastResponse>({ endpoint: Endpoint.WEATHER.FORECAST, params: (params ?? {}) as Record<string, any> }),
  historical: (params?: WeatherHistoricalParams): Promise<WeatherHistoricalResponse> => apiService.get<WeatherHistoricalResponse>({ endpoint: Endpoint.WEATHER.HISTORICAL, params: (params ?? {}) as Record<string, any> }),
  exportSchedule: (data: WeatherExportScheduleParams): Promise<WeatherExportScheduleResponse> => apiService.post<WeatherExportScheduleResponse>({ endpoint: Endpoint.WEATHER.EXPORT_SCHEDULE, data: (data ?? {}) as Record<string, any> }),
};

export default weatherService;
