// AUTO-GENERATED by app-tsx-codegen.
// Source of truth: /planner/ui_pages/*/page.json

import { Toaster } from '@/components/ui/toaster';
import { CustomToastProvider } from '@/components/ui/custom-toast-manager';
import { TooltipProvider } from '@/components/ui/tooltip';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { ThemeProvider } from '@/contexts/ThemeContext';
import { AuthProvider, useAuth } from '@/contexts/AuthContext';
import ErrorBoundary from '@/components/ErrorBoundary';
import ProtectedRoute from '@/components/ProtectedRoute';
import PublicRoute from '@/components/PublicRoute';
import AppLayout from '@/components/AppLayout';
import PublicLayout from '@/components/PublicLayout';
import AdvisoryCreation from '@/pages/AdvisoryCreation';
import AgriculturalInformation from '@/pages/AgriculturalInformation';
import AIModels from '@/pages/AIModels';
import AlertsReports from '@/pages/AlertsReports';
import BeneficiaryDetail from '@/pages/BeneficiaryDetail';
import BeneficiaryTracking from '@/pages/BeneficiaryTracking';
import CropMonitoring from '@/pages/CropMonitoring';
import CropRecommendations from '@/pages/CropRecommendations';
import CustomQueries from '@/pages/CustomQueries';
import DataHub from '@/pages/DataHub';
import DistrictMaps from '@/pages/DistrictMaps';
import FarmerDirectory from '@/pages/FarmerDirectory';
import FarmerProfile from '@/pages/FarmerProfile';
import FarmFieldDetail from '@/pages/FarmFieldDetail';
import FarmManagement from '@/pages/FarmManagement';
import FieldVisits from '@/pages/FieldVisits';
import ImpactAssessment from '@/pages/ImpactAssessment';
import Landing from '@/pages/Landing';
import MarketPrices from '@/pages/MarketPrices';
import MonitoringDashboard from '@/pages/MonitoringDashboard';
import MyFarm from '@/pages/MyFarm';
import NationalStatistics from '@/pages/NationalStatistics';
import PestDiseaseReports from '@/pages/PestDiseaseReports';
import PestDiseaseWarnings from '@/pages/PestDiseaseWarnings';
import PolicyDashboard from '@/pages/PolicyDashboard';
import ProductionReports from '@/pages/ProductionReports';
import ProgrammeKPIs from '@/pages/ProgrammeKPIs';
import PublicMaps from '@/pages/PublicMaps';
import PublicReports from '@/pages/PublicReports';
import ResearchOutputDetail from '@/pages/ResearchOutputDetail';
import ResearchOutputs from '@/pages/ResearchOutputs';
import SeasonalCalendars from '@/pages/SeasonalCalendars';
import Settings from '@/pages/Settings';
import StatisticalAnalysis from '@/pages/StatisticalAnalysis';
import WeatherAlerts from '@/pages/WeatherAlerts';
import WeatherData from '@/pages/WeatherData';
import Login from '@/pages/Login';
import Signup from '@/pages/Signup';
import VerifyOtp from '@/pages/VerifyOtp';
import ForgotPassword from '@/pages/ForgotPassword';
import VerifyResetOtp from '@/pages/VerifyResetOtp';
import ResetPassword from '@/pages/ResetPassword';

const queryClient = new QueryClient();

function RoleHomeRedirect() {
  const { user } = useAuth();
  let role = (user?.role ?? '').toLowerCase();
  if (!role && user?.email) {
    role = (user.email.split('@')[0] ?? '').toLowerCase().replace(/\d+$/, '');
  }
  if (role === 'extension worker') return <Navigate to='/farm-management' replace />;
  if (role === 'researcher') return <Navigate to='/data-hub' replace />;
  if (role === 'maaif official') return <Navigate to='/policy-dashboard' replace />;
  if (role === 'development partner') return <Navigate to='/monitoring-dashboard' replace />;
  if (role === 'farmer') return <Navigate to='/weather-alerts' replace />;
  if (role === 'public visitor') return <Navigate to='/public-maps' replace />;
  return <Navigate to='/farm-management' replace />;
}

function IndexRoute() {
  const { isAuthenticated } = useAuth();
  if (isAuthenticated) return <RoleHomeRedirect />;
  return <Landing />;
}

const App = () => (
  <QueryClientProvider client={queryClient}>
    <TooltipProvider>
      <Toaster />
      <CustomToastProvider>
        <ThemeProvider>
          <AuthProvider>
            <ErrorBoundary>
              <BrowserRouter>
                <Routes>
                  <Route path='/login' element={<PublicRoute><Login /></PublicRoute>} />
                  <Route path='/signup' element={<PublicRoute><Signup /></PublicRoute>} />
                  <Route path='/verify-otp' element={<PublicRoute><VerifyOtp /></PublicRoute>} />
                  <Route path='/forgot-password' element={<PublicRoute><ForgotPassword /></PublicRoute>} />
                  <Route path='/verify-reset-otp' element={<PublicRoute><VerifyResetOtp /></PublicRoute>} />
                  <Route path='/reset-password' element={<PublicRoute><ResetPassword /></PublicRoute>} />

                  <Route element={<PublicLayout />}>
                    <Route index element={<IndexRoute />} />
                    <Route path='/public-maps' element={<PublicMaps />} />
                    <Route path='/agricultural-information' element={<AgriculturalInformation />} />
                    <Route path='/seasonal-calendars' element={<SeasonalCalendars />} />
                  </Route>

                  <Route element={<ProtectedRoute><AppLayout /></ProtectedRoute>}>
                    <Route path='farm-management' element={<ProtectedRoute requiredPermission='extension worker'><FarmManagement /></ProtectedRoute>} />
                    <Route path='advisory-creation' element={<ProtectedRoute requiredPermission='extension worker'><AdvisoryCreation /></ProtectedRoute>} />
                    <Route path='farmer-directory' element={<ProtectedRoute requiredPermission='extension worker'><FarmerDirectory /></ProtectedRoute>} />
                    <Route path='field-visits' element={<ProtectedRoute requiredPermission='extension worker'><FieldVisits /></ProtectedRoute>} />
                    <Route path='alerts-reports' element={<ProtectedRoute requiredPermission='extension worker'><AlertsReports /></ProtectedRoute>} />
                    <Route path='data-hub' element={<ProtectedRoute requiredPermission='researcher'><DataHub /></ProtectedRoute>} />
                    <Route path='ai-models' element={<ProtectedRoute requiredPermission='researcher'><AIModels /></ProtectedRoute>} />
                    <Route path='statistical-analysis' element={<ProtectedRoute requiredPermission='researcher'><StatisticalAnalysis /></ProtectedRoute>} />
                    <Route path='custom-queries' element={<ProtectedRoute requiredPermission='researcher'><CustomQueries /></ProtectedRoute>} />
                    <Route path='research-outputs' element={<ProtectedRoute requiredPermission='researcher'><ResearchOutputs /></ProtectedRoute>} />
                    <Route path='weather-data' element={<ProtectedRoute requiredPermission='researcher'><WeatherData /></ProtectedRoute>} />
                    <Route path='policy-dashboard' element={<ProtectedRoute requiredPermission='maaif official'><PolicyDashboard /></ProtectedRoute>} />
                    <Route path='national-statistics' element={<ProtectedRoute requiredPermission='maaif official'><NationalStatistics /></ProtectedRoute>} />
                    <Route path='production-reports' element={<ProtectedRoute requiredPermission='maaif official'><ProductionReports /></ProtectedRoute>} />
                    <Route path='pest-disease-reports' element={<ProtectedRoute requiredPermission='maaif official'><PestDiseaseReports /></ProtectedRoute>} />
                    <Route path='district-maps' element={<ProtectedRoute requiredPermission='maaif official'><DistrictMaps /></ProtectedRoute>} />
                    <Route path='monitoring-dashboard' element={<ProtectedRoute requiredPermission='development partner'><MonitoringDashboard /></ProtectedRoute>} />
                    <Route path='impact-assessment' element={<ProtectedRoute requiredPermission='development partner'><ImpactAssessment /></ProtectedRoute>} />
                    <Route path='programme-kpis' element={<ProtectedRoute requiredPermission='development partner'><ProgrammeKPIs /></ProtectedRoute>} />
                    <Route path='beneficiary-tracking' element={<ProtectedRoute requiredPermission='development partner'><BeneficiaryTracking /></ProtectedRoute>} />
                    <Route path='public-reports' element={<ProtectedRoute requiredPermission='farmer,extension worker,researcher,maaif official,development partner,public visitor'><PublicReports /></ProtectedRoute>} />
                    <Route path='settings' element={<ProtectedRoute requiredPermission='farmer,extension worker,researcher,maaif official,development partner,public visitor'><Settings /></ProtectedRoute>} />
                    <Route path='weather-alerts' element={<ProtectedRoute requiredPermission='farmer'><WeatherAlerts /></ProtectedRoute>} />
                    <Route path='pest-disease-warnings' element={<ProtectedRoute requiredPermission='farmer'><PestDiseaseWarnings /></ProtectedRoute>} />
                    <Route path='crop-recommendations' element={<ProtectedRoute requiredPermission='farmer'><CropRecommendations /></ProtectedRoute>} />
                    <Route path='crop-monitoring' element={<ProtectedRoute requiredPermission='farmer,extension worker,researcher,maaif official'><CropMonitoring /></ProtectedRoute>} />
                    <Route path='my-farm' element={<ProtectedRoute requiredPermission='farmer'><MyFarm /></ProtectedRoute>} />
                    <Route path='market-prices' element={<ProtectedRoute requiredPermission='farmer'><MarketPrices /></ProtectedRoute>} />
                    <Route path='farmer-directory/:id' element={<ProtectedRoute requiredPermission='extension worker'><FarmerProfile /></ProtectedRoute>} />
                    <Route path='research-outputs/:id' element={<ProtectedRoute requiredPermission='researcher'><ResearchOutputDetail /></ProtectedRoute>} />
                    <Route path='beneficiary-tracking/:id' element={<ProtectedRoute requiredPermission='development partner'><BeneficiaryDetail /></ProtectedRoute>} />
                    <Route path='my-farm/:id' element={<ProtectedRoute requiredPermission='farmer'><FarmFieldDetail /></ProtectedRoute>} />
                  </Route>
                  <Route path='*' element={<Navigate to='/' replace />} />
                </Routes>
              </BrowserRouter>
            </ErrorBoundary>
          </AuthProvider>
        </ThemeProvider>
      </CustomToastProvider>
    </TooltipProvider>
  </QueryClientProvider>
);

export default App;
